# Exploratory Data Analysis
This notebook is used to explore the initial dataset and see what we have to work with

Importing the dataset and saving it to a variable:

In [40]:
import pandas as pd
pd.options.display.max_columns = None

weapons_df = pd.read_csv('data/amcdata_weapons_facilities_V2.csv', encoding='latin-1')

Getting an overview of the dataset (head):

In [49]:
weapons_df.head(5)

,agreement_id,Item_letter,Item_number,item_type,item,facility,weapon_item_definition,c_weapon_item_definition,subcategory,subcategory_main,summary_category,ban_development,c_ban_development,ban_development_execution_type,ban_development_assistance_grant,c_ban_development_assistance_grant,ban_development_assistance_gain,c_ban_development_assistance_gain,ban_development_permission,c_ban_development_permission,ban_development_execution,c_ban_development_execution,ban_development_party,ban_development_party_specific,c_ban_development_party_specific,ban_testing,c_testing_,ban_testing_execution_type,ban_testing_assistance_grant,c_ban_testing_assistance_grant,ban_testing_assistance_gain,c_ban_tesing_assistance_gain,ban_testing_permission,c_ban_testing_permission,ban_testing_execution,c_ban_testing_execution,ban_testing_party,ban_testing_party_specific,c_ban_testing_party_specific,ban_production,c_ban_production,ban_production_execution_type,ban_production_assistance_grant,c_ban_priduction_assistance_grant,ban_production_assistance_gain,c_ban_production_assistance_gain,ban_production_permission,c_ban_production_permission,ban_production_execution,c_ban_production_execution,ban_production_party,ban_production_party_specific,c_ban_production_party_specific,ban_acquisition,c_ban_acquisition,ban_acquisition_execution_type,ban_acquisition_assistance_grant,c_ban_acquisition_assistance_grant,ban_acquisition_assistance_gain,c_ban_acquisition_assistance_gain,ban_acquisition_permission,c_ban_acquisition_permission,ban_acquisition_execution,c_ban_acquisition_execution,ban_acquisition_party,ban_acquisition_party_specific,c_ban_acquisition_party_specific,ban_possession,c_ban_possession,ban_possession_general,c_ban_possession_general,ban_possession_general_execution_type,ban_possession_general_assistance_grant,c_ban_possession_general_assistance_grant,ban_possession_general_assistance_gain,c_ban_possession_general_assistance_gain,ban_possession_general_permission,c_ban_possession_general_permission,ban_possession_general_execution,c_ban_possession_general_execution,ban_possession_party,ban_possession_party_specific,c_ban_possession_party_specific,ban_possession_non_deployed,c_ban_possession_non_deployed,ban_possession_non_deployed_execution_type,ban_possession_non_deployed_assistance_grant,c_ban_possession_non_deployed_assistance_grant,ban_possession_non_deployed_assistance_gain,c_ban_possession_non_deployed_assistance_gain,ban_possession_non_deployed_permission,c_ban_possession_non_deployed_permission,ban_possession_non_deployed_execution,c_ban_possession_non_deployed_execution,ban_possession_non_deployed_party,ban_possession_non_deployed_party_specific,c_ban_possession_non_deployed_party_specific,ban_possession_deployed,c_ban_possession_deployed,ban_possession_deployed_execution_type,ban_possession_deployed_assistance_grant,c_ban_possession_deployed_assistance_grant,ban_possession_deployed_assistance_gain,c_ban_possession_deployed_assistance_gain,ban_possession_deployed_permission,c_ban_possession_deployed_permission,ban_possession_deployed_execution,c_ban_possession_deployed_execution,ban_possession_deployed_party,ban_possession_deployed_party_specific,c_ban_possession_deployed_party_specific,ban_station,c_ban_station,ban_station_execution_type,ban_station_assistance_grant,c_ban_station_assistance_grant,ban_station_assistance_gain,c_ban_station_assistance_gain,ban_station_permission,c_ban_station_permission,ban_station_execution,c_ban_station_execution,ban_station_party,ban_station_party_specific,c_ban_station_party_specific,ban_transfer,c_ban_transfer,ban_transfer_execution_type,ban_transfer_assistance_grant,c_ban_transfer_assistance_grant,ban_transfer_assistance_gain,c_ban_transfer_assistance_gain,ban_transfer_permission,c_ban_transfer_permission,ban_transfer_execution,c_ban_transfer_execution,ban_transfer_party,ban_transfer_party_specific,c_ban_transfer_party_specific,ban_use,c_ban_use,ban_use_execution_type,ban_use_assistance_grant,c_ban_use_assistance_grant,ban_use_assistance_gain,c_ban_use_assistance_gain,ban_use_permission,c_ban_use_permission,ban_use_execution,c_ban_use_execution,ban_use_party,ban_use_party_specific,c_ban_use_party_specific,ban_disposal,c_ban_disposal,ban_disposal_interaction_type,ban_disposal_assistance_grant,c_ban_disposal_assistance_grant,ban_disposal_assistance_gain,c_ban_disposal_assistance_gain,ban_disposal_permission,c_ban_disposal_permission,ban_disposal_execution,c_ban_disposal_execution,ban_disposal_party,ban_disposal_party_specific,c_ban_disposal_party_specific,restriction_development,c_restriction_development,restriction_development_party,restriction_development_party_specific,c_restriction_development_party_specific,restriction_development_location,restriction_development_location_specific,c_restriction_development_location_specific,restriction_development_facility,restriction_development_facility_specific,c_restriction_development_facility_specific,restriction_development_quality,restriction_development_quality_practice,restriction_development_quality_practice_specified,restriction_development_quality_capability,restriction_development_quality_capability_specific,c_restriction_development_quality_specific,restriction_development_quantity,restriction_development_quantity_specific,c_restriction_development_quantity_specific,restriction_development_quantity_type,restriction_development_quantity_type_other,c_restriction_development_quantity_type,restriction_development_item_counting,c_restriction_development_item_counting,restriction_development_item_counting_point,c_restriction_development_item_counting_point,testing_restriction,c_testing_restriction,restriction_testing_party,restriction_testing_party_specific,c_restriction_testing_party_specific,restriction_testing_location,restriction_testing_location_specific,c_restriction_testing_location_specific,restriction_testing_facility,restriction_testing_facility_specific,c_restriction_testing_facility_specific,restriction_testing_quality,restriction_testing_quality_practice,restriction_testing_quality_practice_specified,restriction_testing_quality_capability,restriction_testing_quality_capability_specific,c_restriction_testing_quality_specific,restriction_testing_quantity,restriction_testing_quantity_specific,c_restriction_testing_quantity_specific,restriction_testing_quantity_type,restriction_testing_quantity_type_other,c_restriction_testing_quantity_type,restriction_testing_item_counting,c_restriction_testing_item_counting,restriction_testing_item_counting_point,c_restriction_testing_item_counting_point,restriction_production,c_restriction_production,restriction_production_party,restriction_production_party_specific,c_restriction_production_party_specific,restriction_production_location,restriction_production_location_specific,c_restriction_production_location_specific,restriction_production_facility,restriction_production_facility_specific,c_restriction_production_facility_specific,restriction_production_quality,restriction_production_quality_practice,restriction_production_quality_practice_specified,restriction_production_quality_capability,restriction_production_quality_capability_specific,c_restriction_production_quality_specific,restriction_production_quantity,restriction_production_quantity_specific,c_restriction_production_quantity_specific,restriction_production_quantity_type,restriction_production_quantity_type_other,c_restriction_production_quantity_type,restriction_production_item_counting,c_restriction_production_item_counting,restriction_production_item_counting_point,c_restriction_production_item_counting_point,restriction_acquisition,c_restriction_acquisition,restriction_acquisition_party,restriction_acquisition_party_specific,c_restriction_acquisition_party_specific,restriction_acquisition_location,restriction_acquisition_location_specific,c_restriction_acquisition_location_specific,restriction_acquisition_facility,restriction_acquisition_facility_specific,c_restriction_acquisition_facility_specific,restriction_acquisition_quality,restriction_acquisition_quality_practice,restriction_acquisition_quality_practice_specified,restriction_acquisition_quality_capability,restriction_acquisition_quality_capability_specific,c_restriction_acquisition_quality_specific,restriction_acquisition_quantity,restriction_acquisition_quantity_specific,c_restriction_acquisition_quantity_specific,restriction_acquisition_quantity_type,restriction_acquisition_quantity_type_other,c_restriction_acquisition_quantity_type,restriction_acquisition_item_counting,c_restriction_acquisition_item_counting,restriction_acquisition_item_counting_point,c_restriction_acquisition_item_counting_point,restriction_possession,c_restriction_possession,restriction_possession_general,c_restriction_possession_general,restriction_possession_general_party,restriction_possession_general_party_specific,c_restriction_possession_general_party_specific,restriction_possession_general_location,restriction_possession_general_location_specific,c_restriction_possession_general_location_specific,restriction_possession_general_facility,restriction_possession_general_facility_specific,c_restriction_possession_general_facility_specific,restriction_possession_general_quality,restriction_possession_general_quality_practice,restriction_possession_general_quality_practice_specified,restriction_possession_general_quality_capability,restriction_possession_general_quality_capability_specific,c_restriction_possession_general_quality_specific,restriction_possession_general_quantity,restriction_possession_general_quantity_specific,c_restriction_possession_general_quantity_specific,restriction_possession_general_quantity_type,restriction_possession_general_quantity_type_other,c_restriction_possession_general_quantity_type,restriction_possession_general_item_counting,c_restriction_possession_general_item_counting,restriction_possession_general_item_counting_point,c_restriction_possession_general_item_counting_point,restriction_possession_non_deployed,c_restriction_possession_non_deployed,restriction_possession_non_deployed_party,restriction_possession_non_deployed_party_specific,c_restriction_possession_non_deployed_party_specific,restriction_possession_non_deployed_location,restriction_possession_non_deployed_location_specific,c_restriction_possession_non_deployed_location_specific,restriction_possession_non_deployed_facility,restriction_possession_non_deployed_facility_specific,c_restriction_possession_non_deployed_facility_specific,restriction_possession_non_deployed_quality,restriction_possession_non_deployed_quality_practice,restriction_possession_non_deployed_quality_practice_specified,restriction_possession_non_deployed_quality_capability,restriction_possession_non_deployed_quality_capability_specific,c_restriction_possession_non_deployed_quality_specific,restriction_possession_non_deployed_quantity,restriction_possession_non_deployed_quantity_specific,c_restriction_possession_non_deployed_quantity_specific,restriction_possession_non_deployed_quantity_type,restriction_possession_non_deployed_quantity_type_other,c_restriction_possession_non_deployed_quantity_type,restriction_possession_non_deployed_item_counting,c_restriction_possession_non_deployed_item_counting,restriction_possession_non_deployed_item_counting_point,c_restriction_possession_non_deployed_item_counting_point,restriction_possession_deployed,c_restriction_possession_deployed,restriction_possession_deployed_party,restriction_possession_deployed_party_specific,c_restriction_possession_deployed_party_specific,restriction_possession_deployed_location,restriction_possession_deployed_location_specific,c_restriction_possession_deployed_location_specific,restriction_possession_deployed_facility,restriction_possession_deployed_facility_specific,c_restriction_possession_deployed_facility_specific,restriction_possession_deployed_quality,restriction_possession_deployed_quality_practice,restriction_possession_deployed_quality_practice_specified,restriction_possession_deployed_quality_capability,restriction_possession_deployed_quality_capability_specific,c_restriction_possession_deployed_quality_specific,restriction_possession_deployed_quantity,restriction_possession_deployed_quantity_specific,c_restriction_possession_deployed_quantity_specific,restriction_possession_deployed_quantity_type,restriction_possession_deployed_quantity_type_other,c_restriction_possession_deployed_quantity_type,restriction_possession_deployed_item_counting,c_restriction_possession_deployed_item_counting,restriction_possession_deployed_item_counting_point,c_restriction_possession_deployed_item_counting_point,restriction_transfer,c_restriction_transfer,restriction_transfer_party,restriction_transfer_party_specific,c_restriction_transfer_party_specific,restriction_transfer_location,restriction_transfer_location_specific,c_restriction_transfer_location_specific,restriction_transfer_facility,restriction_transfer_facility_specific,c_restriction_transfer_facility_specific,restriction_transfer_quality,restriction_transfer_quality_practice,restriction_transfer_quality_practice_specified,restriction_transfer_quality_capability,restriction_transfer_quality_capability_specific,c_restriction_transfer_quality_specific,restriction_transfer_quantity,restriction_transfer_quantity_specific,c_restriction_transfer_quantity_specific,restriction_transfer_quantity_type,restriction_transfer_quantity_type_other,c_restriction_transfer_quantity_type,restriction_transfer_item_counting,c_restriction_transfer_item_counting,restriction_transfer_item_counting_point,c_restriction_transfer_item_counting_point,restriction_use,c_restriction_use,restriction_use_party,restriction_use_party_specific,c_restriction_use_party_specific,restriction_use_location,restriction_use_location_specific,c_restriction_use_location_specific,restriction_use_facility,restriction_use_facility_specific,c_restriction_use_facility_specific,restriction_use_quality,restriction_use_quality_practice,restriction_use_quality_practice_specified,restriction_use_quality_capability,restriction_use_quality_capability_specific,c_restriction_use_quality_specific,restriction_use_quantity,restriction_use_quantity_specific,c_restriction_use_quanity_specific,restriction_use_quantity_type,restriction_use_quantity_type_other,c_restriction_use_quantity_type,restriction_use_item_counting,c_restriction_use_item_counting,restriction_use_item_counting_point,c_restriction_use_item_counting_point,restriction_disposal,c_restriction_disposal,restriction_disposal_party,restriction_disposal_party_specific,c_restriction_disposal_party_specific,restriction_disposal_location,restriction_disposal_location_specific,c_restriction_disposal_location_specific,restriction_disposal_facility,restriction_disposal_facility_specific,c_restriction_disposal_facility_specific,restriction_disposal_quality,restriction_disposal_quality_practice,restriction_disposal_quality_practice_specified,restriction_disposal_quality_capability,restriction_disposal_quality_capability_specific,c_restriction_disposal_quality_specific,restriction_disposal_quantity,restriction_disposal_quantity_specific,c_restriction_disposal_quanity_specific,restriction_disposal_quantity_type,restriction_disaposal_quantity_type_other,c_restriction_disposal_quantity_type,restriction_disaposal_item_counting_point,c_restriction_disaposal_item_counting_point,restriction_disposal_item_counting_point,c_restriction_disposal_item_counting_point,facility_destruction,facility_destruction_specified,c_facility_destriction,facility_conversion,facility_conversion_specified,c_facility_conversion,facility_use,facility_use_specified,c_facility_use,eliminitation,elimination_procedure,c_elimination,point_of_elimination,c_point_of_elimination,conversion,conversion_procedure,c_conversion_procedure,point_of_conversion,c_point_of_conversion,modernization,modernization_other,c_modernization,obligations_timeframe_type,timeframe_set_time,timeframe_other,c_obligations_timeframe,timeframe_phases,c_timeframe_phases,phases_number,c_phases,timeframe_obligations_extention,timeframe_obligations_extention_specified,c_timeframe_obligations_extention_specified,excepetions,excepetions_specified,c_excpetions,Unnamed: 475,Unnamed: 476,Unnamed: 477,Unnamed: 478,Unnamed: 479,Unnamed: 480,Unnamed: 481,Unnamed: 482,Unnamed: 483,Unnamed: 484,Unnamed: 485,Unnamed: 486,Unnamed: 487,Unnamed: 488,Unnamed: 489,Unnamed: 490,Unnamed: 491,Unnamed: 492,Unnamed: 493,Unnamed: 494,Unnamed: 495,Unnamed: 496,Unnamed: 497,Unnamed: 498,Unnamed: 499,Unnamed: 500,Unnamed: 501
0,40,A,1.0,1.0,Weapons General,NaN,99,NaN,NaN,NaN,0.0,0,NaN,0,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,0.0,NaN,0.0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,0.0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,NaN,0,0.0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,0.0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,0.0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,0.0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,0.0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,0.0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0.0,NaN,NaN,0.0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Iid. Article I: The Contracting Parties confir...,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,1,1.0,Quality-specific Use-restriction: restricting ...,0.0,NaN,Ibid. Article I: The Contracting Parties confi...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,0.0,NaN,NaN,Assumed directly upon force given no explicit ...,0.0,NaN,NaN,NaN,2.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Group by weapon type and count:

0. Weapons & ammunition
1. Facility
2. Materials/components
3. Other
4. Interceptor missiles, launchers and radars

In [50]:
weapons_groupby_type_df = weapons_df.groupby(['item_type']).size()
weapons_groupby_type_df

item_type
0.0     61
1.0    308
2.0     29
3.0     28
4.0      5
dtype: int64

Group by weapon item and count:

In [52]:
weapons_groupby_item_df = weapons_df
weapons_groupby_item_df['item'] = weapons_groupby_item_df['item'].str.strip()
pd.options.display.max_rows = 500 
weapons_groupby_item_df['item'].value_counts()

item
Summary Category A (Nuclear Weapons)                                                                                      30
Nuclear Weapons                                                                                                           21
Summary Category B (Conventional Weapons Land)                                                                            14
Weapons General                                                                                                            9
Summary Category D (Conventional Weapons Air)                                                                              8
Fissile Material                                                                                                           7
Nuclear Explosive Devises                                                                                                  7
Summary Category C (Conventional Weapons Sea)                                                                              6
Radioactive Waste                                                                                                          6
Small Arms and Light Weapons                                                                                               6
Summary Category I (ICBM Launchers)                                                                                        5
ICBM Launchers                                                                                                             5
ICBMs                                                                                                                      5
Summary Category G (ICBMs)                                                                                                 5
SLBM Launchers                                                                                                             4
Summary Category H (SLBMs)                                                                                                 4
Summary Category K (Heavy Bombers)                                                                                         4
Summary Category J (SLBM Launchers)                                                                                        4
SLBMs                                                                                                                      4
Heavy Bombers                                                                                                              4
ABM Interceptor Missiles                                                                                                   4
Battle Tanks                                                                                                               3
Chemical Weapons                                                                                                           3
Armoured Combat Vehicles                                                                                                   3
Nuclear Material                                                                                                           3
Submarines                                                                                                                 3
ABM Radars                                                                                                                 3
Attack Helicopters                                                                                                         3
Aircraft Carriers                                                                                                          3
ABM Launchers                                                                                                              3
Ballistic Missiles                                                                                                         3
Mines                                                                                                                      2
Other Devises                                                                                                              2
Combat Aircrafts                                                                                                           2
Booby Traps                                                                                                                2
Aircrafts                                                                                                                  2
Weapons of Mass Destruction                                                                                                2
Ships                                                                                                                      2
Heavy ICBMs                                                                                                                2
Destroyers                                                                                                                 2
Capital Ships                                                                                                              2
Artillery                                                                                                                  2
Objects Carrying Nuclear Weapons                                                                                           2
Ballistic Missile Submarines                                                                                               2
Early Warning Radars                                                                                                       2
ABM Interceptor Missiles (Destruction procedures only)                                                                     2
Non-ABM Missiles, Launchers and Radars                                                                                     2
Test Heavy Bombers                                                                                                         2
ASBMs                                                                                                                      2
Strategic Offensive Arms                                                                                                   2
Merchant Ships                                                                                                             2
Launchers for ICBMs of Older Types Deployed Prior to 1964                                                                  1
Intermediate-range Missile Launchers                                                                                       1
Intermediate-range Missiles                                                                                                1
Nuclear Materials                                                                                                          1
IRM Support Equipment                                                                                                      1
ICBM Test/Training Launchers                                                                                               1
Nuclear Explosive Devices                                                                                                  1
Launchers for Light ICBMs                                                                                                  1
Microbial/Other Biological Agents                                                                                          1
Toxins                                                                                                                     1
Weapons and Equipment and Means of Delivery for Agreement-restricted Toxins and Agents                                     1
Other Weapons of Mass Destruction                                                                                          1
Nuclear Missiles                                                                                                           1
Shorter-range Missiles                                                                                                     1
Shorter-range Missile Launchers                                                                                            1
SRM Support Equipment                                                                                                      1
IRM Support Structures                                                                                                     1
Parts and Components                                                                                                       1
Warheads Attributed to Heavy Bombers                                                                                       1
Missiles and Missile Launchers                                                                                             1
Summary Category E (Biological Weapons)                                                                                    1
Cluster Munition                                                                                                           1
Strategic Nuclear Warheads                                                                                                 1
Anti-personnel Mines                                                                                                       1
Incendiary Weapons                                                                                                         1
Certain Booby Traps                                                                                                        1
Mines Other than Remotely Delivered Mines                                                                                  1
Summary Category F (Chemical Weapons)                                                                                      1
Weapons with the Primary Effect to Injure by Non-detectable Fragments                                                      1
Schedule 1 Chemicals                                                                                                       1
Schedule 2 Chemicals                                                                                                       1
Schedule 3 Chemicals                                                                                                       1
Large Calibre Artillery Systems                                                                                            1
Warships                                                                                                                   1
SLBM Test/Training Launchers                                                                                               1
Remotely Delivered Mines                                                                                                   1
Anti-personel Mines other than Remotely Delivered Mines                                                                    1
Explosive Ordnance                                                                                                         1
Air-delivered Incendiary Weapons                                                                                           1
Laser Weapons                                                                                                              1
Surface Vessels                                                                                                            1
Light Cruisers                                                                                                             1
Heavy Cruisers                                                                                                             1
Vessels of War                                                                                                             1
Vessels of War other than a Captial Ship or Arcraft Carrier                                                                1
Explosive Reminants of War                                                                                                 1
Light Surface Vessels                                                                                                      1
Capital Ships A                                                                                                            1
Conventional Weapons                                                                                                       1
Related Materials                                                                                                          1
Explosives                                                                                                                 1
Ammunition                                                                                                                 1
Warheads Attributed to SLBMs                                                                                               1
Ammunition/Munition                                                                                                        1
Warheads Attributed to ICBMs                                                                                               1
Summary Category L (Nuclear Submarines)                                                                                    1
ABM Lauchers (Destruction procedures only)                                                                                 1
Automatic or Semi-automatic Rapid Reload Systems for ABM launchers                                                         1
Capital Ships B                                                                                                            1
Firearms                                                                                                                   1
Air Defense Radars                                                                                                         1
Phased Array Radars(3M+)                                                                                                   1
Phased Array Radars(3M-)                                                                                                   1
Air Defense Components                                                                                                     1
Space-based Interseptor Missiles other than Strategic Ballistic Missiles                                                   1
Prototype ICBMs                                                                                                            1
Mobile Launchers of Prototype ICBMs                                                                                        1
Test Launchers of ICBMs                                                                                                    1
Silo Training Launchers                                                                                                    1
Prototype SLBMs                                                                                                            1
Test Launchers of SLBMs                                                                                                    1
ABM Radars (Destruction procedures only)                                                                                   1
ICBM Warheads                                                                                                              1
SLBM Warheads                                                                                                              1
ICBMs Equipped with MIRVs                                                                                                  1
Heavy Bomber Nuclear Armaments/Warheads                                                                                    1
Fixed ICBM Launchers                                                                                                       1
Launchers for ICBMs Equipped with MIRV                                                                                     1
ICBM Silo Launchers                                                                                                        1
New Types of ICBMs                                                                                                         1
Launchers of Light ICBMs (or ICBMs of Older Types Deployed Prior to 1964)                                                  1
Launchers for SLBMs Equipped with MIRV                                                                                     1
ASBMs Equipped with MIRVs                                                                                                  1
Cruise Missiles                                                                                                            1
Non-ICBM Land-based Ballistic Missile launchers                                                                            1
Systems for Rapid Reload of ICBM Launchers                                                                                 1
ICBMs of a Retired or Former Type                                                                                          1
ABM Radar Complexes (Destruction procedures only)                                                                          1
ICBM Equipped with MIRV                                                                                                    1
ICBMs for Mobile Launchers of ICBMs                                                                                        1
SLBM Equipped with MIRV                                                                                                    1
SLBMs of a Retired or Former type                                                                                          1
Heavy ICBM Launchers                                                                                                       1
Silo Launchers of ICBMs                                                                                                    1
Silo Launchers of Heavy ICBMs                                                                                              1
Heavy SLBMs                                                                                                                1
Launchers of Heavy SLBMs                                                                                                   1
Former Heavy Bombers                                                                                                       1
Heavy bombers Equipped for Nuclear Armaments other than Long-range Nuclear ALCMs                                           1
Heavy bombers Equipped for Non-nuclear Armaments                                                                           1
Warheads Attributed to Deployed ICBMs and Deployed SLBMs                                                                   1
Warheads Attributed to Deployed ICBMs on Mobile Launchers of ICBMs                                                         1
Warheads Attributed to deployed Heavy Bombers                                                                              1
Rail Mobile Launchers of ICBMs                                                                                             1
Mobile Launchers of Heavy ICBMs                                                                                            1
Transporter Loaders                                                                                                        1
Silos Used as a Launch Control Center                                                                                      1
Soft Site Launchers                                                                                                        1

## Tasks:

Clean up dataset and remove weird summary entries
Find definition of dual-use goods and technologies
Define restriction rate: according to the number of life cycle stages that are restricted?
Is there a way to add weights to each stage?
Do the weights change according to the weapon type?
Difference between banning and resticting?
Find correlations between different data types: are highly explosive weapons highly regulated?


Split main dataset into multiple datasets according to different categories, such as weapon type, item, banned or not, restricted or not, life cycle stage
Separate weapons and facilities

### Remove all rows that are flagged as "summary category"

In [63]:
weapons_nosummary_df = weapons_df[weapons_df['summary_category'] != 1]
weapons_nosummary_df.sample(15)

,agreement_id,Item_letter,Item_number,item_type,item,facility,weapon_item_definition,c_weapon_item_definition,subcategory,subcategory_main,summary_category,ban_development,c_ban_development,ban_development_execution_type,ban_development_assistance_grant,c_ban_development_assistance_grant,ban_development_assistance_gain,c_ban_development_assistance_gain,ban_development_permission,c_ban_development_permission,ban_development_execution,c_ban_development_execution,ban_development_party,ban_development_party_specific,c_ban_development_party_specific,ban_testing,c_testing_,ban_testing_execution_type,ban_testing_assistance_grant,c_ban_testing_assistance_grant,ban_testing_assistance_gain,c_ban_tesing_assistance_gain,ban_testing_permission,c_ban_testing_permission,ban_testing_execution,c_ban_testing_execution,ban_testing_party,ban_testing_party_specific,c_ban_testing_party_specific,ban_production,c_ban_production,ban_production_execution_type,ban_production_assistance_grant,c_ban_priduction_assistance_grant,ban_production_assistance_gain,c_ban_production_assistance_gain,ban_production_permission,c_ban_production_permission,ban_production_execution,c_ban_production_execution,ban_production_party,ban_production_party_specific,c_ban_production_party_specific,ban_acquisition,c_ban_acquisition,ban_acquisition_execution_type,ban_acquisition_assistance_grant,c_ban_acquisition_assistance_grant,ban_acquisition_assistance_gain,c_ban_acquisition_assistance_gain,ban_acquisition_permission,c_ban_acquisition_permission,ban_acquisition_execution,c_ban_acquisition_execution,ban_acquisition_party,ban_acquisition_party_specific,c_ban_acquisition_party_specific,ban_possession,c_ban_possession,ban_possession_general,c_ban_possession_general,ban_possession_general_execution_type,ban_possession_general_assistance_grant,c_ban_possession_general_assistance_grant,ban_possession_general_assistance_gain,c_ban_possession_general_assistance_gain,ban_possession_general_permission,c_ban_possession_general_permission,ban_possession_general_execution,c_ban_possession_general_execution,ban_possession_party,ban_possession_party_specific,c_ban_possession_party_specific,ban_possession_non_deployed,c_ban_possession_non_deployed,ban_possession_non_deployed_execution_type,ban_possession_non_deployed_assistance_grant,c_ban_possession_non_deployed_assistance_grant,ban_possession_non_deployed_assistance_gain,c_ban_possession_non_deployed_assistance_gain,ban_possession_non_deployed_permission,c_ban_possession_non_deployed_permission,ban_possession_non_deployed_execution,c_ban_possession_non_deployed_execution,ban_possession_non_deployed_party,ban_possession_non_deployed_party_specific,c_ban_possession_non_deployed_party_specific,ban_possession_deployed,c_ban_possession_deployed,ban_possession_deployed_execution_type,ban_possession_deployed_assistance_grant,c_ban_possession_deployed_assistance_grant,ban_possession_deployed_assistance_gain,c_ban_possession_deployed_assistance_gain,ban_possession_deployed_permission,c_ban_possession_deployed_permission,ban_possession_deployed_execution,c_ban_possession_deployed_execution,ban_possession_deployed_party,ban_possession_deployed_party_specific,c_ban_possession_deployed_party_specific,ban_station,c_ban_station,ban_station_execution_type,ban_station_assistance_grant,c_ban_station_assistance_grant,ban_station_assistance_gain,c_ban_station_assistance_gain,ban_station_permission,c_ban_station_permission,ban_station_execution,c_ban_station_execution,ban_station_party,ban_station_party_specific,c_ban_station_party_specific,ban_transfer,c_ban_transfer,ban_transfer_execution_type,ban_transfer_assistance_grant,c_ban_transfer_assistance_grant,ban_transfer_assistance_gain,c_ban_transfer_assistance_gain,ban_transfer_permission,c_ban_transfer_permission,ban_transfer_execution,c_ban_transfer_execution,ban_transfer_party,ban_transfer_party_specific,c_ban_transfer_party_specific,ban_use,c_ban_use,ban_use_execution_type,ban_use_assistance_grant,c_ban_use_assistance_grant,ban_use_assistance_gain,c_ban_use_assistance_gain,ban_use_permission,c_ban_use_permission,ban_use_execution,c_ban_use_execution,ban_use_party,ban_use_party_specific,c_ban_use_party_specific,ban_disposal,c_ban_disposal,ban_disposal_interaction_type,ban_disposal_assistance_grant,c_ban_disposal_assistance_grant,ban_disposal_assistance_gain,c_ban_disposal_assistance_gain,ban_disposal_permission,c_ban_disposal_permission,ban_disposal_execution,c_ban_disposal_execution,ban_disposal_party,ban_disposal_party_specific,c_ban_disposal_party_specific,restriction_development,c_restriction_development,restriction_development_party,restriction_development_party_specific,c_restriction_development_party_specific,restriction_development_location,restriction_development_location_specific,c_restriction_development_location_specific,restriction_development_facility,restriction_development_facility_specific,c_restriction_development_facility_specific,restriction_development_quality,restriction_development_quality_practice,restriction_development_quality_practice_specified,restriction_development_quality_capability,restriction_development_quality_capability_specific,c_restriction_development_quality_specific,restriction_development_quantity,restriction_development_quantity_specific,c_restriction_development_quantity_specific,restriction_development_quantity_type,restriction_development_quantity_type_other,c_restriction_development_quantity_type,restriction_development_item_counting,c_restriction_development_item_counting,restriction_development_item_counting_point,c_restriction_development_item_counting_point,testing_restriction,c_testing_restriction,restriction_testing_party,restriction_testing_party_specific,c_restriction_testing_party_specific,restriction_testing_location,restriction_testing_location_specific,c_restriction_testing_location_specific,restriction_testing_facility,restriction_testing_facility_specific,c_restriction_testing_facility_specific,restriction_testing_quality,restriction_testing_quality_practice,restriction_testing_quality_practice_specified,restriction_testing_quality_capability,restriction_testing_quality_capability_specific,c_restriction_testing_quality_specific,restriction_testing_quantity,restriction_testing_quantity_specific,c_restriction_testing_quantity_specific,restriction_testing_quantity_type,restriction_testing_quantity_type_other,c_restriction_testing_quantity_type,restriction_testing_item_counting,c_restriction_testing_item_counting,restriction_testing_item_counting_point,c_restriction_testing_item_counting_point,restriction_production,c_restriction_production,restriction_production_party,restriction_production_party_specific,c_restriction_production_party_specific,restriction_production_location,restriction_production_location_specific,c_restriction_production_location_specific,restriction_production_facility,restriction_production_facility_specific,c_restriction_production_facility_specific,restriction_production_quality,restriction_production_quality_practice,restriction_production_quality_practice_specified,restriction_production_quality_capability,restriction_production_quality_capability_specific,c_restriction_production_quality_specific,restriction_production_quantity,restriction_production_quantity_specific,c_restriction_production_quantity_specific,restriction_production_quantity_type,restriction_production_quantity_type_other,c_restriction_production_quantity_type,restriction_production_item_counting,c_restriction_production_item_counting,restriction_production_item_counting_point,c_restriction_production_item_counting_point,restriction_acquisition,c_restriction_acquisition,restriction_acquisition_party,restriction_acquisition_party_specific,c_restriction_acquisition_party_specific,restriction_acquisition_location,restriction_acquisition_location_specific,c_restriction_acquisition_location_specific,restriction_acquisition_facility,restriction_acquisition_facility_specific,c_restriction_acquisition_facility_specific,restriction_acquisition_quality,restriction_acquisition_quality_practice,restriction_acquisition_quality_practice_specified,restriction_acquisition_quality_capability,restriction_acquisition_quality_capability_specific,c_restriction_acquisition_quality_specific,restriction_acquisition_quantity,restriction_acquisition_quantity_specific,c_restriction_acquisition_quantity_specific,restriction_acquisition_quantity_type,restriction_acquisition_quantity_type_other,c_restriction_acquisition_quantity_type,restriction_acquisition_item_counting,c_restriction_acquisition_item_counting,restriction_acquisition_item_counting_point,c_restriction_acquisition_item_counting_point,restriction_possession,c_restriction_possession,restriction_possession_general,c_restriction_possession_general,restriction_possession_general_party,restriction_possession_general_party_specific,c_restriction_possession_general_party_specific,restriction_possession_general_location,restriction_possession_general_location_specific,c_restriction_possession_general_location_specific,restriction_possession_general_facility,restriction_possession_general_facility_specific,c_restriction_possession_general_facility_specific,restriction_possession_general_quality,restriction_possession_general_quality_practice,restriction_possession_general_quality_practice_specified,restriction_possession_general_quality_capability,restriction_possession_general_quality_capability_specific,c_restriction_possession_general_quality_specific,restriction_possession_general_quantity,restriction_possession_general_quantity_specific,c_restriction_possession_general_quantity_specific,restriction_possession_general_quantity_type,restriction_possession_general_quantity_type_other,c_restriction_possession_general_quantity_type,restriction_possession_general_item_counting,c_restriction_possession_general_item_counting,restriction_possession_general_item_counting_point,c_restriction_possession_general_item_counting_point,restriction_possession_non_deployed,c_restriction_possession_non_deployed,restriction_possession_non_deployed_party,restriction_possession_non_deployed_party_specific,c_restriction_possession_non_deployed_party_specific,restriction_possession_non_deployed_location,restriction_possession_non_deployed_location_specific,c_restriction_possession_non_deployed_location_specific,restriction_possession_non_deployed_facility,restriction_possession_non_deployed_facility_specific,c_restriction_possession_non_deployed_facility_specific,restriction_possession_non_deployed_quality,restriction_possession_non_deployed_quality_practice,restriction_possession_non_deployed_quality_practice_specified,restriction_possession_non_deployed_quality_capability,restriction_possession_non_deployed_quality_capability_specific,c_restriction_possession_non_deployed_quality_specific,restriction_possession_non_deployed_quantity,restriction_possession_non_deployed_quantity_specific,c_restriction_possession_non_deployed_quantity_specific,restriction_possession_non_deployed_quantity_type,restriction_possession_non_deployed_quantity_type_other,c_restriction_possession_non_deployed_quantity_type,restriction_possession_non_deployed_item_counting,c_restriction_possession_non_deployed_item_counting,restriction_possession_non_deployed_item_counting_point,c_restriction_possession_non_deployed_item_counting_point,restriction_possession_deployed,c_restriction_possession_deployed,restriction_possession_deployed_party,restriction_possession_deployed_party_specific,c_restriction_possession_deployed_party_specific,restriction_possession_deployed_location,restriction_possession_deployed_location_specific,c_restriction_possession_deployed_location_specific,restriction_possession_deployed_facility,restriction_possession_deployed_facility_specific,c_restriction_possession_deployed_facility_specific,restriction_possession_deployed_quality,restriction_possession_deployed_quality_practice,restriction_possession_deployed_quality_practice_specified,restriction_possession_deployed_quality_capability,restriction_possession_deployed_quality_capability_specific,c_restriction_possession_deployed_quality_specific,restriction_possession_deployed_quantity,restriction_possession_deployed_quantity_specific,c_restriction_possession_deployed_quantity_specific,restriction_possession_deployed_quantity_type,restriction_possession_deployed_quantity_type_other,c_restriction_possession_deployed_quantity_type,restriction_possession_deployed_item_counting,c_restriction_possession_deployed_item_counting,restriction_possession_deployed_item_counting_point,c_restriction_possession_deployed_item_counting_point,restriction_transfer,c_restriction_transfer,restriction_transfer_party,restriction_transfer_party_specific,c_restriction_transfer_party_specific,restriction_transfer_location,restriction_transfer_location_specific,c_restriction_transfer_location_specific,restriction_transfer_facility,restriction_transfer_facility_specific,c_restriction_transfer_facility_specific,restriction_transfer_quality,restriction_transfer_quality_practice,restriction_transfer_quality_practice_specified,restriction_transfer_quality_capability,restriction_transfer_quality_capability_specific,c_restriction_transfer_quality_specific,restriction_transfer_quantity,restriction_transfer_quantity_specific,c_restriction_transfer_quantity_specific,restriction_transfer_quantity_type,restriction_transfer_quantity_type_other,c_restriction_transfer_quantity_type,restriction_transfer_item_counting,c_restriction_transfer_item_counting,restriction_transfer_item_counting_point,c_restriction_transfer_item_counting_point,restriction_use,c_restriction_use,restriction_use_party,restriction_use_party_specific,c_restriction_use_party_specific,restriction_use_location,restriction_use_location_specific,c_restriction_use_location_specific,restriction_use_facility,restriction_use_facility_specific,c_restriction_use_facility_specific,restriction_use_quality,restriction_use_quality_practice,restriction_use_quality_practice_specified,restriction_use_quality_capability,restriction_use_quality_capability_specific,c_restriction_use_quality_specific,restriction_use_quantity,restriction_use_quantity_specific,c_restriction_use_quanity_specific,restriction_use_quantity_type,restriction_use_quantity_type_other,c_restriction_use_quantity_type,restriction_use_item_counting,c_restriction_use_item_counting,restriction_use_item_counting_point,c_restriction_use_item_counting_point,restriction_disposal,c_restriction_disposal,restriction_disposal_party,restriction_disposal_party_specific,c_restriction_disposal_party_specific,restriction_disposal_location,restriction_disposal_location_specific,c_restriction_disposal_location_specific,restriction_disposal_facility,restriction_disposal_facility_specific,c_restriction_disposal_facility_specific,restriction_disposal_quality,restriction_disposal_quality_practice,restriction_disposal_quality_practice_specified,restriction_disposal_quality_capability,restriction_disposal_quality_capability_specific,c_restriction_disposal_quality_specific,restriction_disposal_quantity,restriction_disposal_quantity_specific,c_restriction_disposal_quanity_specific,restriction_disposal_quantity_type,restriction_disaposal_quantity_type_other,c_restriction_disposal_quantity_type,restriction_disaposal_item_counting_point,c_restriction_disaposal_item_counting_point,restriction_disposal_item_counting_point,c_restriction_disposal_item_counting_point,facility_destruction,facility_destruction_specified,c_facility_destriction,facility_conversion,facility_conversion_specified,c_facility_conversion,facility_use,facility_use_specified,c_facility_use,eliminitation,elimination_procedure,c_elimination,point_of_elimination,c_point_of_elimination,conversion,conversion_procedure,c_conversion_procedure,point_of_conversion,c_point_of_conversion,modernization,modernization_other,c_modernization,obligations_timeframe_type,timeframe_set_time,timeframe_other,c_obligations_timeframe,timeframe_phases,c_timeframe_phases,phases_number,c_phases,timeframe_obligations_extention,timeframe_obligations_extention_specified,c_timeframe_obligations_extention_specified,excepetions,excepetions_specified,c_excpetions,Unnamed: 475,Unnamed: 476,Unnamed: 477,Unnamed: 478,Unnamed: 479,Unnamed: 480,Unnamed: 481,Unnamed: 482,Unnamed: 483,Unnamed: 484,Unnamed: 485,Unnamed: 486,Unnamed: 487,Unnamed: 488,Unnamed: 489,Unnamed: 490,Unnamed: 491,Unnamed: 492,Unnamed: 493,Unnamed: 494,Unnamed: 495,Unnamed: 496,Unnamed: 497,Unnamed: 498,Unnamed: 499,Unnamed: 500,Unnamed: 501
407,8,U,21.0,0.0,Destroyers,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,NaN,0,NaN,NaN,1,Germany cannot construct new warships and must...,0,NaN,NaN,0,NaN,0,NaN,0,NaN,1,Germany,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,NaN,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,NaN,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,NaN,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,NaN,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,NaN,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,1,Article 181-190,1,Germany,Article 181,1,âFrom the date of the coming into force of t...,Article 184,0,NaN,NaN,1,NaN,NaN,1.0,42 modern destroyers must be âsurrendered to...,Article 185,1,Maximum possession of 12 destroyers,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Article 189.,1.0,Germany,Article 189,0.0,NaN,NaN,0,NaN,NaN,1,1.0,Selling and discarding of items from dismantle...,0.0,NaN,Article 189,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Group by item (name of the object):

In [66]:
weapons_groupby_item_df = weapons_nosummary_df
# strip
weapons_groupby_item_df['item'] = weapons_groupby_item_df['item'].str.strip()
# increase no. of rows displayed
pd.options.display.max_rows = 500
weapons_groupby_item_df = weapons_groupby_item_df['item'].value_counts()
weapons_groupby_item_df

/tmp/ipykernel_27177/3362324243.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weapons_groupby_item_df['item'] = weapons_groupby_item_df['item'].str.strip()

item
Nuclear Weapons                                                                                                           19
Weapons General                                                                                                            9
Fissile Material                                                                                                           7
Nuclear Explosive Devises                                                                                                  7
Radioactive Waste                                                                                                          6
Small Arms and Light Weapons                                                                                               6
ICBMs                                                                                                                      5
ICBM Launchers                                                                                                             5
SLBMs                                                                                                                      4
SLBM Launchers                                                                                                             4
Heavy Bombers                                                                                                              4
ABM Interceptor Missiles                                                                                                   4
Nuclear Material                                                                                                           3
Submarines                                                                                                                 3
Summary Category A (Nuclear Weapons)                                                                                       3
Battle Tanks                                                                                                               3
Armoured Combat Vehicles                                                                                                   3
Chemical Weapons                                                                                                           3
Attack Helicopters                                                                                                         3
ABM Launchers                                                                                                              3
Aircraft Carriers                                                                                                          3
ABM Radars                                                                                                                 3
Ballistic Missiles                                                                                                         3
Ballistic Missile Submarines                                                                                               2
Other Devises                                                                                                              2
Booby Traps                                                                                                                2
Combat Aircrafts                                                                                                           2
Weapons of Mass Destruction                                                                                                2
Objects Carrying Nuclear Weapons                                                                                           2
Ships                                                                                                                      2
Mines                                                                                                                      2
Merchant Ships                                                                                                             2
Artillery                                                                                                                  2
Capital Ships                                                                                                              2
Destroyers                                                                                                                 2
Heavy ICBMs                                                                                                                2
Early Warning Radars                                                                                                       2
ABM Interceptor Missiles (Destruction procedures only)                                                                     2
Non-ABM Missiles, Launchers and Radars                                                                                     2
Test Heavy Bombers                                                                                                         2
ASBMs                                                                                                                      2
Strategic Offensive Arms                                                                                                   2
Aircrafts                                                                                                                  2
Strategic Nuclear Warheads                                                                                                 1
Cluster Munition                                                                                                           1
Nuclear Materials                                                                                                          1
Anti-personnel Mines                                                                                                       1
SRM Support Equipment                                                                                                      1
Nuclear Explosive Devices                                                                                                  1
Shorter-range Missiles                                                                                                     1
Shorter-range Missile Launchers                                                                                            1
IRM Support Equipment                                                                                                      1
IRM Support Structures                                                                                                     1
Intermediate-range Missiles                                                                                                1
Intermediate-range Missile Launchers                                                                                       1
Parts and Components                                                                                                       1
Ammunition/Munition                                                                                                        1
Missiles and Missile Launchers                                                                                             1
Warheads Attributed to Heavy Bombers                                                                                       1
Other Weapons of Mass Destruction                                                                                          1
Microbial/Other Biological Agents                                                                                          1
Toxins                                                                                                                     1
Weapons and Equipment and Means of Delivery for Agreement-restricted Toxins and Agents                                     1
Incendiary Weapons                                                                                                         1
Certain Booby Traps                                                                                                        1
Mines Other than Remotely Delivered Mines                                                                                  1
Schedule 3 Chemicals                                                                                                       1
Weapons with the Primary Effect to Injure by Non-detectable Fragments                                                      1
Warships                                                                                                                   1
Schedule 1 Chemicals                                                                                                       1
Schedule 2 Chemicals                                                                                                       1
Large Calibre Artillery Systems                                                                                            1
Launchers for Light ICBMs                                                                                                  1
Warheads Attributed to SLBMs                                                                                               1
Remotely Delivered Mines                                                                                                   1
Anti-personel Mines other than Remotely Delivered Mines                                                                    1
Explosive Ordnance                                                                                                         1
Air-delivered Incendiary Weapons                                                                                           1
Laser Weapons                                                                                                              1
Surface Vessels                                                                                                            1
Light Cruisers                                                                                                             1
Heavy Cruisers                                                                                                             1
Vessels of War                                                                                                             1
Vessels of War other than a Captial Ship or Arcraft Carrier                                                                1
Explosive Reminants of War                                                                                                 1
Light Surface Vessels                                                                                                      1
Capital Ships A                                                                                                            1
Conventional Weapons                                                                                                       1
Related Materials                                                                                                          1
Explosives                                                                                                                 1
Ammunition                                                                                                                 1
Warheads Attributed to ICBMs                                                                                               1
SLBM Test/Training Launchers                                                                                               1
ICBM Test/Training Launchers                                                                                               1
Launchers for ICBMs of Older Types Deployed Prior to 1964                                                                  1
ABM Lauchers (Destruction procedures only)                                                                                 1
Automatic or Semi-automatic Rapid Reload Systems for ABM launchers                                                         1
Capital Ships B                                                                                                            1
Firearms                                                                                                                   1
Air Defense Radars                                                                                                         1
Phased Array Radars(3M+)                                                                                                   1
Phased Array Radars(3M-)                                                                                                   1
Air Defense Components                                                                                                     1
Space-based Interseptor Missiles other than Strategic Ballistic Missiles                                                   1
Prototype ICBMs                                                                                                            1
Mobile Launchers of Prototype ICBMs                                                                                        1
Test Launchers of ICBMs                                                                                                    1
Silo Training Launchers                                                                                                    1
Prototype SLBMs                                                                                                            1
Test Launchers of SLBMs                                                                                                    1
ABM Radars (Destruction procedures only)                                                                                   1
ICBM Warheads                                                                                                              1
SLBM Warheads                                                                                                              1
ICBMs Equipped with MIRVs                                                                                                  1
Heavy Bomber Nuclear Armaments/Warheads                                                                                    1
Fixed ICBM Launchers                                                                                                       1
Launchers for ICBMs Equipped with MIRV                                                                                     1
ICBM Silo Launchers                                                                                                        1
New Types of ICBMs                                                                                                         1
Launchers of Light ICBMs (or ICBMs of Older Types Deployed Prior to 1964)                                                  1
Launchers for SLBMs Equipped with MIRV                                                                                     1
ASBMs Equipped with MIRVs                                                                                                  1
Cruise Missiles                                                                                                            1
Non-ICBM Land-based Ballistic Missile launchers                                                                            1
Systems for Rapid Reload of ICBM Launchers                                                                                 1
ICBMs of a Retired or Former Type                                                                                          1
ABM Radar Complexes (Destruction procedures only)                                                                          1
ICBM Equipped with MIRV                                                                                                    1
ICBMs for Mobile Launchers of ICBMs                                                                                        1
SLBM Equipped with MIRV                                                                                                    1
SLBMs of a Retired or Former type                                                                                          1
Heavy ICBM Launchers                                                                                                       1
Silo Launchers of ICBMs                                                                                                    1
Silo Launchers of Heavy ICBMs                                                                                              1
Heavy SLBMs                                                                                                                1
Launchers of Heavy SLBMs                                                                                                   1
Former Heavy Bombers                                                                                                       1
Heavy bombers Equipped for Nuclear Armaments other than Long-range Nuclear ALCMs                                           1
Heavy bombers Equipped for Non-nuclear Armaments                                                                           1
Warheads Attributed to Deployed ICBMs and Deployed SLBMs                                                                   1
Warheads Attributed to Deployed ICBMs on Mobile Launchers of ICBMs                                                         1
Warheads Attributed to deployed Heavy Bombers                                                                              1
Rail Mobile Launchers of ICBMs                                                                                             1
Mobile Launchers of Heavy ICBMs                                                                                            1
Transporter Loaders                                                                                                        1
Silos Used as a Launch Control Center                                                                                      1
Soft Site Launchers                                                                                                        1
Rapid Reload Systems                                                                                                       1
Launchers of Ballistic Missiles                                                                                            1
Systems for Placing Nuclear Weapons into Earth Orbit                                                                       1
Long-range Nuclear ALCMs                                                                                                   1
Aicrafts Other than Airplanes (8000 km+ range)                                                                             1
Aicrafts not Intially Constructed as Bombers (8000 km+ range)                                                              1
Training Heavy Bombers                                                                                                     1
Naval Vessels                                                                                                              1
Fixed Structures for Rail Mobile Launchers of ICBMs                                                                        1
Test Launchers                                                                                                             1
Ammunition and Components                                                                                                  1
Biological Weapons                                                                                                         1

### Group by type:

0. Weapons & ammunition
1. Facility
2. Materials/components
3. Other
4. Interceptor missiles, launchers and radars

In [67]:
weapons_groupby_type_df = weapons_nosummary_df.groupby(['item_type']).size()
weapons_groupby_type_df

item_type
0.0     61
1.0    228
2.0     29
3.0     28
4.0      5
dtype: int64

### Select only those items which have had one of its life cycle stages banned

In [74]:
ban_columns = ['ban_development', 'ban_testing', 'ban_production', 'ban_acquisition', 'ban_possession', 'ban_transfer', 'ban_station', 'ban_use', 'ban_disposal']
weapons_banned_df = weapons_nosummary_df[weapons_nosummary_df[ban_columns].any(axis=1)]
weapons_banned_df.sample(10)

,agreement_id,Item_letter,Item_number,item_type,item,facility,weapon_item_definition,c_weapon_item_definition,subcategory,subcategory_main,summary_category,ban_development,c_ban_development,ban_development_execution_type,ban_development_assistance_grant,c_ban_development_assistance_grant,ban_development_assistance_gain,c_ban_development_assistance_gain,ban_development_permission,c_ban_development_permission,ban_development_execution,c_ban_development_execution,ban_development_party,ban_development_party_specific,c_ban_development_party_specific,ban_testing,c_testing_,ban_testing_execution_type,ban_testing_assistance_grant,c_ban_testing_assistance_grant,ban_testing_assistance_gain,c_ban_tesing_assistance_gain,ban_testing_permission,c_ban_testing_permission,ban_testing_execution,c_ban_testing_execution,ban_testing_party,ban_testing_party_specific,c_ban_testing_party_specific,ban_production,c_ban_production,ban_production_execution_type,ban_production_assistance_grant,c_ban_priduction_assistance_grant,ban_production_assistance_gain,c_ban_production_assistance_gain,ban_production_permission,c_ban_production_permission,ban_production_execution,c_ban_production_execution,ban_production_party,ban_production_party_specific,c_ban_production_party_specific,ban_acquisition,c_ban_acquisition,ban_acquisition_execution_type,ban_acquisition_assistance_grant,c_ban_acquisition_assistance_grant,ban_acquisition_assistance_gain,c_ban_acquisition_assistance_gain,ban_acquisition_permission,c_ban_acquisition_permission,ban_acquisition_execution,c_ban_acquisition_execution,ban_acquisition_party,ban_acquisition_party_specific,c_ban_acquisition_party_specific,ban_possession,c_ban_possession,ban_possession_general,c_ban_possession_general,ban_possession_general_execution_type,ban_possession_general_assistance_grant,c_ban_possession_general_assistance_grant,ban_possession_general_assistance_gain,c_ban_possession_general_assistance_gain,ban_possession_general_permission,c_ban_possession_general_permission,ban_possession_general_execution,c_ban_possession_general_execution,ban_possession_party,ban_possession_party_specific,c_ban_possession_party_specific,ban_possession_non_deployed,c_ban_possession_non_deployed,ban_possession_non_deployed_execution_type,ban_possession_non_deployed_assistance_grant,c_ban_possession_non_deployed_assistance_grant,ban_possession_non_deployed_assistance_gain,c_ban_possession_non_deployed_assistance_gain,ban_possession_non_deployed_permission,c_ban_possession_non_deployed_permission,ban_possession_non_deployed_execution,c_ban_possession_non_deployed_execution,ban_possession_non_deployed_party,ban_possession_non_deployed_party_specific,c_ban_possession_non_deployed_party_specific,ban_possession_deployed,c_ban_possession_deployed,ban_possession_deployed_execution_type,ban_possession_deployed_assistance_grant,c_ban_possession_deployed_assistance_grant,ban_possession_deployed_assistance_gain,c_ban_possession_deployed_assistance_gain,ban_possession_deployed_permission,c_ban_possession_deployed_permission,ban_possession_deployed_execution,c_ban_possession_deployed_execution,ban_possession_deployed_party,ban_possession_deployed_party_specific,c_ban_possession_deployed_party_specific,ban_station,c_ban_station,ban_station_execution_type,ban_station_assistance_grant,c_ban_station_assistance_grant,ban_station_assistance_gain,c_ban_station_assistance_gain,ban_station_permission,c_ban_station_permission,ban_station_execution,c_ban_station_execution,ban_station_party,ban_station_party_specific,c_ban_station_party_specific,ban_transfer,c_ban_transfer,ban_transfer_execution_type,ban_transfer_assistance_grant,c_ban_transfer_assistance_grant,ban_transfer_assistance_gain,c_ban_transfer_assistance_gain,ban_transfer_permission,c_ban_transfer_permission,ban_transfer_execution,c_ban_transfer_execution,ban_transfer_party,ban_transfer_party_specific,c_ban_transfer_party_specific,ban_use,c_ban_use,ban_use_execution_type,ban_use_assistance_grant,c_ban_use_assistance_grant,ban_use_assistance_gain,c_ban_use_assistance_gain,ban_use_permission,c_ban_use_permission,ban_use_execution,c_ban_use_execution,ban_use_party,ban_use_party_specific,c_ban_use_party_specific,ban_disposal,c_ban_disposal,ban_disposal_interaction_type,ban_disposal_assistance_grant,c_ban_disposal_assistance_grant,ban_disposal_assistance_gain,c_ban_disposal_assistance_gain,ban_disposal_permission,c_ban_disposal_permission,ban_disposal_execution,c_ban_disposal_execution,ban_disposal_party,ban_disposal_party_specific,c_ban_disposal_party_specific,restriction_development,c_restriction_development,restriction_development_party,restriction_development_party_specific,c_restriction_development_party_specific,restriction_development_location,restriction_development_location_specific,c_restriction_development_location_specific,restriction_development_facility,restriction_development_facility_specific,c_restriction_development_facility_specific,restriction_development_quality,restriction_development_quality_practice,restriction_development_quality_practice_specified,restriction_development_quality_capability,restriction_development_quality_capability_specific,c_restriction_development_quality_specific,restriction_development_quantity,restriction_development_quantity_specific,c_restriction_development_quantity_specific,restriction_development_quantity_type,restriction_development_quantity_type_other,c_restriction_development_quantity_type,restriction_development_item_counting,c_restriction_development_item_counting,restriction_development_item_counting_point,c_restriction_development_item_counting_point,testing_restriction,c_testing_restriction,restriction_testing_party,restriction_testing_party_specific,c_restriction_testing_party_specific,restriction_testing_location,restriction_testing_location_specific,c_restriction_testing_location_specific,restriction_testing_facility,restriction_testing_facility_specific,c_restriction_testing_facility_specific,restriction_testing_quality,restriction_testing_quality_practice,restriction_testing_quality_practice_specified,restriction_testing_quality_capability,restriction_testing_quality_capability_specific,c_restriction_testing_quality_specific,restriction_testing_quantity,restriction_testing_quantity_specific,c_restriction_testing_quantity_specific,restriction_testing_quantity_type,restriction_testing_quantity_type_other,c_restriction_testing_quantity_type,restriction_testing_item_counting,c_restriction_testing_item_counting,restriction_testing_item_counting_point,c_restriction_testing_item_counting_point,restriction_production,c_restriction_production,restriction_production_party,restriction_production_party_specific,c_restriction_production_party_specific,restriction_production_location,restriction_production_location_specific,c_restriction_production_location_specific,restriction_production_facility,restriction_production_facility_specific,c_restriction_production_facility_specific,restriction_production_quality,restriction_production_quality_practice,restriction_production_quality_practice_specified,restriction_production_quality_capability,restriction_production_quality_capability_specific,c_restriction_production_quality_specific,restriction_production_quantity,restriction_production_quantity_specific,c_restriction_production_quantity_specific,restriction_production_quantity_type,restriction_production_quantity_type_other,c_restriction_production_quantity_type,restriction_production_item_counting,c_restriction_production_item_counting,restriction_production_item_counting_point,c_restriction_production_item_counting_point,restriction_acquisition,c_restriction_acquisition,restriction_acquisition_party,restriction_acquisition_party_specific,c_restriction_acquisition_party_specific,restriction_acquisition_location,restriction_acquisition_location_specific,c_restriction_acquisition_location_specific,restriction_acquisition_facility,restriction_acquisition_facility_specific,c_restriction_acquisition_facility_specific,restriction_acquisition_quality,restriction_acquisition_quality_practice,restriction_acquisition_quality_practice_specified,restriction_acquisition_quality_capability,restriction_acquisition_quality_capability_specific,c_restriction_acquisition_quality_specific,restriction_acquisition_quantity,restriction_acquisition_quantity_specific,c_restriction_acquisition_quantity_specific,restriction_acquisition_quantity_type,restriction_acquisition_quantity_type_other,c_restriction_acquisition_quantity_type,restriction_acquisition_item_counting,c_restriction_acquisition_item_counting,restriction_acquisition_item_counting_point,c_restriction_acquisition_item_counting_point,restriction_possession,c_restriction_possession,restriction_possession_general,c_restriction_possession_general,restriction_possession_general_party,restriction_possession_general_party_specific,c_restriction_possession_general_party_specific,restriction_possession_general_location,restriction_possession_general_location_specific,c_restriction_possession_general_location_specific,restriction_possession_general_facility,restriction_possession_general_facility_specific,c_restriction_possession_general_facility_specific,restriction_possession_general_quality,restriction_possession_general_quality_practice,restriction_possession_general_quality_practice_specified,restriction_possession_general_quality_capability,restriction_possession_general_quality_capability_specific,c_restriction_possession_general_quality_specific,restriction_possession_general_quantity,restriction_possession_general_quantity_specific,c_restriction_possession_general_quantity_specific,restriction_possession_general_quantity_type,restriction_possession_general_quantity_type_other,c_restriction_possession_general_quantity_type,restriction_possession_general_item_counting,c_restriction_possession_general_item_counting,restriction_possession_general_item_counting_point,c_restriction_possession_general_item_counting_point,restriction_possession_non_deployed,c_restriction_possession_non_deployed,restriction_possession_non_deployed_party,restriction_possession_non_deployed_party_specific,c_restriction_possession_non_deployed_party_specific,restriction_possession_non_deployed_location,restriction_possession_non_deployed_location_specific,c_restriction_possession_non_deployed_location_specific,restriction_possession_non_deployed_facility,restriction_possession_non_deployed_facility_specific,c_restriction_possession_non_deployed_facility_specific,restriction_possession_non_deployed_quality,restriction_possession_non_deployed_quality_practice,restriction_possession_non_deployed_quality_practice_specified,restriction_possession_non_deployed_quality_capability,restriction_possession_non_deployed_quality_capability_specific,c_restriction_possession_non_deployed_quality_specific,restriction_possession_non_deployed_quantity,restriction_possession_non_deployed_quantity_specific,c_restriction_possession_non_deployed_quantity_specific,restriction_possession_non_deployed_quantity_type,restriction_possession_non_deployed_quantity_type_other,c_restriction_possession_non_deployed_quantity_type,restriction_possession_non_deployed_item_counting,c_restriction_possession_non_deployed_item_counting,restriction_possession_non_deployed_item_counting_point,c_restriction_possession_non_deployed_item_counting_point,restriction_possession_deployed,c_restriction_possession_deployed,restriction_possession_deployed_party,restriction_possession_deployed_party_specific,c_restriction_possession_deployed_party_specific,restriction_possession_deployed_location,restriction_possession_deployed_location_specific,c_restriction_possession_deployed_location_specific,restriction_possession_deployed_facility,restriction_possession_deployed_facility_specific,c_restriction_possession_deployed_facility_specific,restriction_possession_deployed_quality,restriction_possession_deployed_quality_practice,restriction_possession_deployed_quality_practice_specified,restriction_possession_deployed_quality_capability,restriction_possession_deployed_quality_capability_specific,c_restriction_possession_deployed_quality_specific,restriction_possession_deployed_quantity,restriction_possession_deployed_quantity_specific,c_restriction_possession_deployed_quantity_specific,restriction_possession_deployed_quantity_type,restriction_possession_deployed_quantity_type_other,c_restriction_possession_deployed_quantity_type,restriction_possession_deployed_item_counting,c_restriction_possession_deployed_item_counting,restriction_possession_deployed_item_counting_point,c_restriction_possession_deployed_item_counting_point,restriction_transfer,c_restriction_transfer,restriction_transfer_party,restriction_transfer_party_specific,c_restriction_transfer_party_specific,restriction_transfer_location,restriction_transfer_location_specific,c_restriction_transfer_location_specific,restriction_transfer_facility,restriction_transfer_facility_specific,c_restriction_transfer_facility_specific,restriction_transfer_quality,restriction_transfer_quality_practice,restriction_transfer_quality_practice_specified,restriction_transfer_quality_capability,restriction_transfer_quality_capability_specific,c_restriction_transfer_quality_specific,restriction_transfer_quantity,restriction_transfer_quantity_specific,c_restriction_transfer_quantity_specific,restriction_transfer_quantity_type,restriction_transfer_quantity_type_other,c_restriction_transfer_quantity_type,restriction_transfer_item_counting,c_restriction_transfer_item_counting,restriction_transfer_item_counting_point,c_restriction_transfer_item_counting_point,restriction_use,c_restriction_use,restriction_use_party,restriction_use_party_specific,c_restriction_use_party_specific,restriction_use_location,restriction_use_location_specific,c_restriction_use_location_specific,restriction_use_facility,restriction_use_facility_specific,c_restriction_use_facility_specific,restriction_use_quality,restriction_use_quality_practice,restriction_use_quality_practice_specified,restriction_use_quality_capability,restriction_use_quality_capability_specific,c_restriction_use_quality_specific,restriction_use_quantity,restriction_use_quantity_specific,c_restriction_use_quanity_specific,restriction_use_quantity_type,restriction_use_quantity_type_other,c_restriction_use_quantity_type,restriction_use_item_counting,c_restriction_use_item_counting,restriction_use_item_counting_point,c_restriction_use_item_counting_point,restriction_disposal,c_restriction_disposal,restriction_disposal_party,restriction_disposal_party_specific,c_restriction_disposal_party_specific,restriction_disposal_location,restriction_disposal_location_specific,c_restriction_disposal_location_specific,restriction_disposal_facility,restriction_disposal_facility_specific,c_restriction_disposal_facility_specific,restriction_disposal_quality,restriction_disposal_quality_practice,restriction_disposal_quality_practice_specified,restriction_disposal_quality_capability,restriction_disposal_quality_capability_specific,c_restriction_disposal_quality_specific,restriction_disposal_quantity,restriction_disposal_quantity_specific,c_restriction_disposal_quanity_specific,restriction_disposal_quantity_type,restriction_disaposal_quantity_type_other,c_restriction_disposal_quantity_type,restriction_disaposal_item_counting_point,c_restriction_disaposal_item_counting_point,restriction_disposal_item_counting_point,c_restriction_disposal_item_counting_point,facility_destruction,facility_destruction_specified,c_facility_destriction,facility_conversion,facility_conversion_specified,c_facility_conversion,facility_use,facility_use_specified,c_facility_use,eliminitation,elimination_procedure,c_elimination,point_of_elimination,c_point_of_elimination,conversion,conversion_procedure,c_conversion_procedure,point_of_conversion,c_point_of_conversion,modernization,modernization_other,c_modernization,obligations_timeframe_type,timeframe_set_time,timeframe_other,c_obligations_timeframe,timeframe_phases,c_timeframe_phases,phases_number,c_phases,timeframe_obligations_extention,timeframe_obligations_extention_specified,c_timeframe_obligations_extention_specified,excepetions,excepetions_specified,c_excpetions,Unnamed: 475,Unnamed: 476,Unnamed: 477,Unnamed: 478,Unnamed: 479,Unnamed: 480,Unnamed: 481,Unnamed: 482,Unnamed: 483,Unnamed: 484,Unnamed: 485,Unnamed: 486,Unnamed: 487,Unnamed: 488,Unnamed: 489,Unnamed: 490,Unnamed: 491,Unnamed: 492,Unnamed: 493,Unnamed: 494,Unnamed: 495,Unnamed: 496,Unnamed: 497,Unnamed: 498,Unnamed: 499,Unnamed: 500,Unnamed: 501
112,330,B,2.0,3.0,Fissile Material,NaN,Radioactive Material means material that conta...,Ibid. Article 1:e: radioactive material means ...,NaN,NaN,0.0,0,NaN,0,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,0.0,NaN,0.0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,0.0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,NaN,0,0.0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,0.0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,0.0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,0.0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,0.0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,1,Ibid. Article 3:3: Each State Party also under...,1,1.0,Ibid. Article 3:4: Each State Party undertakes...,1,Ibid. Article 3:4: Each State Party undertakes...,1,Ibid. Article 3:3: Each State Party also under...,1,Ibid. Article 3:3: Each State Party also under...,0,NaN,NaN,0,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,ibid. Article 4:3: Each State Party further un...,0.0,NaN,NaN,0.0,NaN,NaN,0,NaN,NaN,1,1.0,Quality-specific Transfer-restriction: restric...,0.0,NaN,ibid. Article 4:3: Each State Party further un...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Ibid. Article 4:2:a): Each State Party therefo...,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,1,1.0,Quality-specific Use-restriction: restricting ...,0.0,NaN,Ibid. Article 4:2:a): Each State Party therefo...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,0.0,NaN,NaN,Assumed directly upon force given no explicit ...,0.0,NaN,NaN,NaN,2.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Select only those items which have had one of its life cycle stages restricted
!!!! Restrictions on stationing aren't listed in the csv file (no column named restriction_stationing)

In [78]:
restriction_columns = ['restriction_development', 'testing_restriction', 'restriction_production', 'restriction_acquisition', 'restriction_possession', 'restriction_transfer', 'restriction_use', 'restriction_disposal']
weapons_restricted_df = weapons_nosummary_df[weapons_nosummary_df[restriction_columns].any(axis=1)]
weapons_restricted_df.sample(10)

,agreement_id,Item_letter,Item_number,item_type,item,facility,weapon_item_definition,c_weapon_item_definition,subcategory,subcategory_main,summary_category,ban_development,c_ban_development,ban_development_execution_type,ban_development_assistance_grant,c_ban_development_assistance_grant,ban_development_assistance_gain,c_ban_development_assistance_gain,ban_development_permission,c_ban_development_permission,ban_development_execution,c_ban_development_execution,ban_development_party,ban_development_party_specific,c_ban_development_party_specific,ban_testing,c_testing_,ban_testing_execution_type,ban_testing_assistance_grant,c_ban_testing_assistance_grant,ban_testing_assistance_gain,c_ban_tesing_assistance_gain,ban_testing_permission,c_ban_testing_permission,ban_testing_execution,c_ban_testing_execution,ban_testing_party,ban_testing_party_specific,c_ban_testing_party_specific,ban_production,c_ban_production,ban_production_execution_type,ban_production_assistance_grant,c_ban_priduction_assistance_grant,ban_production_assistance_gain,c_ban_production_assistance_gain,ban_production_permission,c_ban_production_permission,ban_production_execution,c_ban_production_execution,ban_production_party,ban_production_party_specific,c_ban_production_party_specific,ban_acquisition,c_ban_acquisition,ban_acquisition_execution_type,ban_acquisition_assistance_grant,c_ban_acquisition_assistance_grant,ban_acquisition_assistance_gain,c_ban_acquisition_assistance_gain,ban_acquisition_permission,c_ban_acquisition_permission,ban_acquisition_execution,c_ban_acquisition_execution,ban_acquisition_party,ban_acquisition_party_specific,c_ban_acquisition_party_specific,ban_possession,c_ban_possession,ban_possession_general,c_ban_possession_general,ban_possession_general_execution_type,ban_possession_general_assistance_grant,c_ban_possession_general_assistance_grant,ban_possession_general_assistance_gain,c_ban_possession_general_assistance_gain,ban_possession_general_permission,c_ban_possession_general_permission,ban_possession_general_execution,c_ban_possession_general_execution,ban_possession_party,ban_possession_party_specific,c_ban_possession_party_specific,ban_possession_non_deployed,c_ban_possession_non_deployed,ban_possession_non_deployed_execution_type,ban_possession_non_deployed_assistance_grant,c_ban_possession_non_deployed_assistance_grant,ban_possession_non_deployed_assistance_gain,c_ban_possession_non_deployed_assistance_gain,ban_possession_non_deployed_permission,c_ban_possession_non_deployed_permission,ban_possession_non_deployed_execution,c_ban_possession_non_deployed_execution,ban_possession_non_deployed_party,ban_possession_non_deployed_party_specific,c_ban_possession_non_deployed_party_specific,ban_possession_deployed,c_ban_possession_deployed,ban_possession_deployed_execution_type,ban_possession_deployed_assistance_grant,c_ban_possession_deployed_assistance_grant,ban_possession_deployed_assistance_gain,c_ban_possession_deployed_assistance_gain,ban_possession_deployed_permission,c_ban_possession_deployed_permission,ban_possession_deployed_execution,c_ban_possession_deployed_execution,ban_possession_deployed_party,ban_possession_deployed_party_specific,c_ban_possession_deployed_party_specific,ban_station,c_ban_station,ban_station_execution_type,ban_station_assistance_grant,c_ban_station_assistance_grant,ban_station_assistance_gain,c_ban_station_assistance_gain,ban_station_permission,c_ban_station_permission,ban_station_execution,c_ban_station_execution,ban_station_party,ban_station_party_specific,c_ban_station_party_specific,ban_transfer,c_ban_transfer,ban_transfer_execution_type,ban_transfer_assistance_grant,c_ban_transfer_assistance_grant,ban_transfer_assistance_gain,c_ban_transfer_assistance_gain,ban_transfer_permission,c_ban_transfer_permission,ban_transfer_execution,c_ban_transfer_execution,ban_transfer_party,ban_transfer_party_specific,c_ban_transfer_party_specific,ban_use,c_ban_use,ban_use_execution_type,ban_use_assistance_grant,c_ban_use_assistance_grant,ban_use_assistance_gain,c_ban_use_assistance_gain,ban_use_permission,c_ban_use_permission,ban_use_execution,c_ban_use_execution,ban_use_party,ban_use_party_specific,c_ban_use_party_specific,ban_disposal,c_ban_disposal,ban_disposal_interaction_type,ban_disposal_assistance_grant,c_ban_disposal_assistance_grant,ban_disposal_assistance_gain,c_ban_disposal_assistance_gain,ban_disposal_permission,c_ban_disposal_permission,ban_disposal_execution,c_ban_disposal_execution,ban_disposal_party,ban_disposal_party_specific,c_ban_disposal_party_specific,restriction_development,c_restriction_development,restriction_development_party,restriction_development_party_specific,c_restriction_development_party_specific,restriction_development_location,restriction_development_location_specific,c_restriction_development_location_specific,restriction_development_facility,restriction_development_facility_specific,c_restriction_development_facility_specific,restriction_development_quality,restriction_development_quality_practice,restriction_development_quality_practice_specified,restriction_development_quality_capability,restriction_development_quality_capability_specific,c_restriction_development_quality_specific,restriction_development_quantity,restriction_development_quantity_specific,c_restriction_development_quantity_specific,restriction_development_quantity_type,restriction_development_quantity_type_other,c_restriction_development_quantity_type,restriction_development_item_counting,c_restriction_development_item_counting,restriction_development_item_counting_point,c_restriction_development_item_counting_point,testing_restriction,c_testing_restriction,restriction_testing_party,restriction_testing_party_specific,c_restriction_testing_party_specific,restriction_testing_location,restriction_testing_location_specific,c_restriction_testing_location_specific,restriction_testing_facility,restriction_testing_facility_specific,c_restriction_testing_facility_specific,restriction_testing_quality,restriction_testing_quality_practice,restriction_testing_quality_practice_specified,restriction_testing_quality_capability,restriction_testing_quality_capability_specific,c_restriction_testing_quality_specific,restriction_testing_quantity,restriction_testing_quantity_specific,c_restriction_testing_quantity_specific,restriction_testing_quantity_type,restriction_testing_quantity_type_other,c_restriction_testing_quantity_type,restriction_testing_item_counting,c_restriction_testing_item_counting,restriction_testing_item_counting_point,c_restriction_testing_item_counting_point,restriction_production,c_restriction_production,restriction_production_party,restriction_production_party_specific,c_restriction_production_party_specific,restriction_production_location,restriction_production_location_specific,c_restriction_production_location_specific,restriction_production_facility,restriction_production_facility_specific,c_restriction_production_facility_specific,restriction_production_quality,restriction_production_quality_practice,restriction_production_quality_practice_specified,restriction_production_quality_capability,restriction_production_quality_capability_specific,c_restriction_production_quality_specific,restriction_production_quantity,restriction_production_quantity_specific,c_restriction_production_quantity_specific,restriction_production_quantity_type,restriction_production_quantity_type_other,c_restriction_production_quantity_type,restriction_production_item_counting,c_restriction_production_item_counting,restriction_production_item_counting_point,c_restriction_production_item_counting_point,restriction_acquisition,c_restriction_acquisition,restriction_acquisition_party,restriction_acquisition_party_specific,c_restriction_acquisition_party_specific,restriction_acquisition_location,restriction_acquisition_location_specific,c_restriction_acquisition_location_specific,restriction_acquisition_facility,restriction_acquisition_facility_specific,c_restriction_acquisition_facility_specific,restriction_acquisition_quality,restriction_acquisition_quality_practice,restriction_acquisition_quality_practice_specified,restriction_acquisition_quality_capability,restriction_acquisition_quality_capability_specific,c_restriction_acquisition_quality_specific,restriction_acquisition_quantity,restriction_acquisition_quantity_specific,c_restriction_acquisition_quantity_specific,restriction_acquisition_quantity_type,restriction_acquisition_quantity_type_other,c_restriction_acquisition_quantity_type,restriction_acquisition_item_counting,c_restriction_acquisition_item_counting,restriction_acquisition_item_counting_point,c_restriction_acquisition_item_counting_point,restriction_possession,c_restriction_possession,restriction_possession_general,c_restriction_possession_general,restriction_possession_general_party,restriction_possession_general_party_specific,c_restriction_possession_general_party_specific,restriction_possession_general_location,restriction_possession_general_location_specific,c_restriction_possession_general_location_specific,restriction_possession_general_facility,restriction_possession_general_facility_specific,c_restriction_possession_general_facility_specific,restriction_possession_general_quality,restriction_possession_general_quality_practice,restriction_possession_general_quality_practice_specified,restriction_possession_general_quality_capability,restriction_possession_general_quality_capability_specific,c_restriction_possession_general_quality_specific,restriction_possession_general_quantity,restriction_possession_general_quantity_specific,c_restriction_possession_general_quantity_specific,restriction_possession_general_quantity_type,restriction_possession_general_quantity_type_other,c_restriction_possession_general_quantity_type,restriction_possession_general_item_counting,c_restriction_possession_general_item_counting,restriction_possession_general_item_counting_point,c_restriction_possession_general_item_counting_point,restriction_possession_non_deployed,c_restriction_possession_non_deployed,restriction_possession_non_deployed_party,restriction_possession_non_deployed_party_specific,c_restriction_possession_non_deployed_party_specific,restriction_possession_non_deployed_location,restriction_possession_non_deployed_location_specific,c_restriction_possession_non_deployed_location_specific,restriction_possession_non_deployed_facility,restriction_possession_non_deployed_facility_specific,c_restriction_possession_non_deployed_facility_specific,restriction_possession_non_deployed_quality,restriction_possession_non_deployed_quality_practice,restriction_possession_non_deployed_quality_practice_specified,restriction_possession_non_deployed_quality_capability,restriction_possession_non_deployed_quality_capability_specific,c_restriction_possession_non_deployed_quality_specific,restriction_possession_non_deployed_quantity,restriction_possession_non_deployed_quantity_specific,c_restriction_possession_non_deployed_quantity_specific,restriction_possession_non_deployed_quantity_type,restriction_possession_non_deployed_quantity_type_other,c_restriction_possession_non_deployed_quantity_type,restriction_possession_non_deployed_item_counting,c_restriction_possession_non_deployed_item_counting,restriction_possession_non_deployed_item_counting_point,c_restriction_possession_non_deployed_item_counting_point,restriction_possession_deployed,c_restriction_possession_deployed,restriction_possession_deployed_party,restriction_possession_deployed_party_specific,c_restriction_possession_deployed_party_specific,restriction_possession_deployed_location,restriction_possession_deployed_location_specific,c_restriction_possession_deployed_location_specific,restriction_possession_deployed_facility,restriction_possession_deployed_facility_specific,c_restriction_possession_deployed_facility_specific,restriction_possession_deployed_quality,restriction_possession_deployed_quality_practice,restriction_possession_deployed_quality_practice_specified,restriction_possession_deployed_quality_capability,restriction_possession_deployed_quality_capability_specific,c_restriction_possession_deployed_quality_specific,restriction_possession_deployed_quantity,restriction_possession_deployed_quantity_specific,c_restriction_possession_deployed_quantity_specific,restriction_possession_deployed_quantity_type,restriction_possession_deployed_quantity_type_other,c_restriction_possession_deployed_quantity_type,restriction_possession_deployed_item_counting,c_restriction_possession_deployed_item_counting,restriction_possession_deployed_item_counting_point,c_restriction_possession_deployed_item_counting_point,restriction_transfer,c_restriction_transfer,restriction_transfer_party,restriction_transfer_party_specific,c_restriction_transfer_party_specific,restriction_transfer_location,restriction_transfer_location_specific,c_restriction_transfer_location_specific,restriction_transfer_facility,restriction_transfer_facility_specific,c_restriction_transfer_facility_specific,restriction_transfer_quality,restriction_transfer_quality_practice,restriction_transfer_quality_practice_specified,restriction_transfer_quality_capability,restriction_transfer_quality_capability_specific,c_restriction_transfer_quality_specific,restriction_transfer_quantity,restriction_transfer_quantity_specific,c_restriction_transfer_quantity_specific,restriction_transfer_quantity_type,restriction_transfer_quantity_type_other,c_restriction_transfer_quantity_type,restriction_transfer_item_counting,c_restriction_transfer_item_counting,restriction_transfer_item_counting_point,c_restriction_transfer_item_counting_point,restriction_use,c_restriction_use,restriction_use_party,restriction_use_party_specific,c_restriction_use_party_specific,restriction_use_location,restriction_use_location_specific,c_restriction_use_location_specific,restriction_use_facility,restriction_use_facility_specific,c_restriction_use_facility_specific,restriction_use_quality,restriction_use_quality_practice,restriction_use_quality_practice_specified,restriction_use_quality_capability,restriction_use_quality_capability_specific,c_restriction_use_quality_specific,restriction_use_quantity,restriction_use_quantity_specific,c_restriction_use_quanity_specific,restriction_use_quantity_type,restriction_use_quantity_type_other,c_restriction_use_quantity_type,restriction_use_item_counting,c_restriction_use_item_counting,restriction_use_item_counting_point,c_restriction_use_item_counting_point,restriction_disposal,c_restriction_disposal,restriction_disposal_party,restriction_disposal_party_specific,c_restriction_disposal_party_specific,restriction_disposal_location,restriction_disposal_location_specific,c_restriction_disposal_location_specific,restriction_disposal_facility,restriction_disposal_facility_specific,c_restriction_disposal_facility_specific,restriction_disposal_quality,restriction_disposal_quality_practice,restriction_disposal_quality_practice_specified,restriction_disposal_quality_capability,restriction_disposal_quality_capability_specific,c_restriction_disposal_quality_specific,restriction_disposal_quantity,restriction_disposal_quantity_specific,c_restriction_disposal_quanity_specific,restriction_disposal_quantity_type,restriction_disaposal_quantity_type_other,c_restriction_disposal_quantity_type,restriction_disaposal_item_counting_point,c_restriction_disaposal_item_counting_point,restriction_disposal_item_counting_point,c_restriction_disposal_item_counting_point,facility_destruction,facility_destruction_specified,c_facility_destriction,facility_conversion,facility_conversion_specified,c_facility_conversion,facility_use,facility_use_specified,c_facility_use,eliminitation,elimination_procedure,c_elimination,point_of_elimination,c_point_of_elimination,conversion,conversion_procedure,c_conversion_procedure,point_of_conversion,c_point_of_conversion,modernization,modernization_other,c_modernization,obligations_timeframe_type,timeframe_set_time,timeframe_other,c_obligations_timeframe,timeframe_phases,c_timeframe_phases,phases_number,c_phases,timeframe_obligations_extention,timeframe_obligations_extention_specified,c_timeframe_obligations_extention_specified,excepetions,excepetions_specified,c_excpetions,Unnamed: 475,Unnamed: 476,Unnamed: 477,Unnamed: 478,Unnamed: 479,Unnamed: 480,Unnamed: 481,Unnamed: 482,Unnamed: 483,Unnamed: 484,Unnamed: 485,Unnamed: 486,Unnamed: 487,Unnamed: 488,Unnamed: 489,Unnamed: 490,Unnamed: 491,Unnamed: 492,Unnamed: 493,Unnamed: 494,Unnamed: 495,Unnamed: 496,Unnamed: 497,Unnamed: 498,Unnamed: 499,Unnamed: 500,Unnamed: 501
140,160,A,1.0,1.0,Nuclear Weapons,NaN,99,NaN,NaN,NaN,0.0,0,NaN,0,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,0.0,NaN,0.0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,0.0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,NaN,0,0.0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,0.0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,0.0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,0.0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,0.0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,0.0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Ibid. Section II.:1.,0,NaN,NaN,1,Location-specific Testing-restriction: restric...,Ibid. Section II.:1.,0,NaN,NaN,1.0,1.0,Location-Quality-specific Testing-restriction:...,0.0,NaN,"Ibid. Article I., Section I.",0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0.0,NaN,NaN,0.0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,0.0,NaN,NaN,Assumed directly upon force given no explicit ...,0.0,NaN,NaN,NaN,2.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Select only weapons

In [88]:
weapons_onlyweapons_df = weapons_nosummary_df[weapons_nosummary_df['item_type'] == 1]
weapons_onlyweapons_df.sample(10)

,agreement_id,Item_letter,Item_number,item_type,item,facility,weapon_item_definition,c_weapon_item_definition,subcategory,subcategory_main,summary_category,ban_development,c_ban_development,ban_development_execution_type,ban_development_assistance_grant,c_ban_development_assistance_grant,ban_development_assistance_gain,c_ban_development_assistance_gain,ban_development_permission,c_ban_development_permission,ban_development_execution,c_ban_development_execution,ban_development_party,ban_development_party_specific,c_ban_development_party_specific,ban_testing,c_testing_,ban_testing_execution_type,ban_testing_assistance_grant,c_ban_testing_assistance_grant,ban_testing_assistance_gain,c_ban_tesing_assistance_gain,ban_testing_permission,c_ban_testing_permission,ban_testing_execution,c_ban_testing_execution,ban_testing_party,ban_testing_party_specific,c_ban_testing_party_specific,ban_production,c_ban_production,ban_production_execution_type,ban_production_assistance_grant,c_ban_priduction_assistance_grant,ban_production_assistance_gain,c_ban_production_assistance_gain,ban_production_permission,c_ban_production_permission,ban_production_execution,c_ban_production_execution,ban_production_party,ban_production_party_specific,c_ban_production_party_specific,ban_acquisition,c_ban_acquisition,ban_acquisition_execution_type,ban_acquisition_assistance_grant,c_ban_acquisition_assistance_grant,ban_acquisition_assistance_gain,c_ban_acquisition_assistance_gain,ban_acquisition_permission,c_ban_acquisition_permission,ban_acquisition_execution,c_ban_acquisition_execution,ban_acquisition_party,ban_acquisition_party_specific,c_ban_acquisition_party_specific,ban_possession,c_ban_possession,ban_possession_general,c_ban_possession_general,ban_possession_general_execution_type,ban_possession_general_assistance_grant,c_ban_possession_general_assistance_grant,ban_possession_general_assistance_gain,c_ban_possession_general_assistance_gain,ban_possession_general_permission,c_ban_possession_general_permission,ban_possession_general_execution,c_ban_possession_general_execution,ban_possession_party,ban_possession_party_specific,c_ban_possession_party_specific,ban_possession_non_deployed,c_ban_possession_non_deployed,ban_possession_non_deployed_execution_type,ban_possession_non_deployed_assistance_grant,c_ban_possession_non_deployed_assistance_grant,ban_possession_non_deployed_assistance_gain,c_ban_possession_non_deployed_assistance_gain,ban_possession_non_deployed_permission,c_ban_possession_non_deployed_permission,ban_possession_non_deployed_execution,c_ban_possession_non_deployed_execution,ban_possession_non_deployed_party,ban_possession_non_deployed_party_specific,c_ban_possession_non_deployed_party_specific,ban_possession_deployed,c_ban_possession_deployed,ban_possession_deployed_execution_type,ban_possession_deployed_assistance_grant,c_ban_possession_deployed_assistance_grant,ban_possession_deployed_assistance_gain,c_ban_possession_deployed_assistance_gain,ban_possession_deployed_permission,c_ban_possession_deployed_permission,ban_possession_deployed_execution,c_ban_possession_deployed_execution,ban_possession_deployed_party,ban_possession_deployed_party_specific,c_ban_possession_deployed_party_specific,ban_station,c_ban_station,ban_station_execution_type,ban_station_assistance_grant,c_ban_station_assistance_grant,ban_station_assistance_gain,c_ban_station_assistance_gain,ban_station_permission,c_ban_station_permission,ban_station_execution,c_ban_station_execution,ban_station_party,ban_station_party_specific,c_ban_station_party_specific,ban_transfer,c_ban_transfer,ban_transfer_execution_type,ban_transfer_assistance_grant,c_ban_transfer_assistance_grant,ban_transfer_assistance_gain,c_ban_transfer_assistance_gain,ban_transfer_permission,c_ban_transfer_permission,ban_transfer_execution,c_ban_transfer_execution,ban_transfer_party,ban_transfer_party_specific,c_ban_transfer_party_specific,ban_use,c_ban_use,ban_use_execution_type,ban_use_assistance_grant,c_ban_use_assistance_grant,ban_use_assistance_gain,c_ban_use_assistance_gain,ban_use_permission,c_ban_use_permission,ban_use_execution,c_ban_use_execution,ban_use_party,ban_use_party_specific,c_ban_use_party_specific,ban_disposal,c_ban_disposal,ban_disposal_interaction_type,ban_disposal_assistance_grant,c_ban_disposal_assistance_grant,ban_disposal_assistance_gain,c_ban_disposal_assistance_gain,ban_disposal_permission,c_ban_disposal_permission,ban_disposal_execution,c_ban_disposal_execution,ban_disposal_party,ban_disposal_party_specific,c_ban_disposal_party_specific,restriction_development,c_restriction_development,restriction_development_party,restriction_development_party_specific,c_restriction_development_party_specific,restriction_development_location,restriction_development_location_specific,c_restriction_development_location_specific,restriction_development_facility,restriction_development_facility_specific,c_restriction_development_facility_specific,restriction_development_quality,restriction_development_quality_practice,restriction_development_quality_practice_specified,restriction_development_quality_capability,restriction_development_quality_capability_specific,c_restriction_development_quality_specific,restriction_development_quantity,restriction_development_quantity_specific,c_restriction_development_quantity_specific,restriction_development_quantity_type,restriction_development_quantity_type_other,c_restriction_development_quantity_type,restriction_development_item_counting,c_restriction_development_item_counting,restriction_development_item_counting_point,c_restriction_development_item_counting_point,testing_restriction,c_testing_restriction,restriction_testing_party,restriction_testing_party_specific,c_restriction_testing_party_specific,restriction_testing_location,restriction_testing_location_specific,c_restriction_testing_location_specific,restriction_testing_facility,restriction_testing_facility_specific,c_restriction_testing_facility_specific,restriction_testing_quality,restriction_testing_quality_practice,restriction_testing_quality_practice_specified,restriction_testing_quality_capability,restriction_testing_quality_capability_specific,c_restriction_testing_quality_specific,restriction_testing_quantity,restriction_testing_quantity_specific,c_restriction_testing_quantity_specific,restriction_testing_quantity_type,restriction_testing_quantity_type_other,c_restriction_testing_quantity_type,restriction_testing_item_counting,c_restriction_testing_item_counting,restriction_testing_item_counting_point,c_restriction_testing_item_counting_point,restriction_production,c_restriction_production,restriction_production_party,restriction_production_party_specific,c_restriction_production_party_specific,restriction_production_location,restriction_production_location_specific,c_restriction_production_location_specific,restriction_production_facility,restriction_production_facility_specific,c_restriction_production_facility_specific,restriction_production_quality,restriction_production_quality_practice,restriction_production_quality_practice_specified,restriction_production_quality_capability,restriction_production_quality_capability_specific,c_restriction_production_quality_specific,restriction_production_quantity,restriction_production_quantity_specific,c_restriction_production_quantity_specific,restriction_production_quantity_type,restriction_production_quantity_type_other,c_restriction_production_quantity_type,restriction_production_item_counting,c_restriction_production_item_counting,restriction_production_item_counting_point,c_restriction_production_item_counting_point,restriction_acquisition,c_restriction_acquisition,restriction_acquisition_party,restriction_acquisition_party_specific,c_restriction_acquisition_party_specific,restriction_acquisition_location,restriction_acquisition_location_specific,c_restriction_acquisition_location_specific,restriction_acquisition_facility,restriction_acquisition_facility_specific,c_restriction_acquisition_facility_specific,restriction_acquisition_quality,restriction_acquisition_quality_practice,restriction_acquisition_quality_practice_specified,restriction_acquisition_quality_capability,restriction_acquisition_quality_capability_specific,c_restriction_acquisition_quality_specific,restriction_acquisition_quantity,restriction_acquisition_quantity_specific,c_restriction_acquisition_quantity_specific,restriction_acquisition_quantity_type,restriction_acquisition_quantity_type_other,c_restriction_acquisition_quantity_type,restriction_acquisition_item_counting,c_restriction_acquisition_item_counting,restriction_acquisition_item_counting_point,c_restriction_acquisition_item_counting_point,restriction_possession,c_restriction_possession,restriction_possession_general,c_restriction_possession_general,restriction_possession_general_party,restriction_possession_general_party_specific,c_restriction_possession_general_party_specific,restriction_possession_general_location,restriction_possession_general_location_specific,c_restriction_possession_general_location_specific,restriction_possession_general_facility,restriction_possession_general_facility_specific,c_restriction_possession_general_facility_specific,restriction_possession_general_quality,restriction_possession_general_quality_practice,restriction_possession_general_quality_practice_specified,restriction_possession_general_quality_capability,restriction_possession_general_quality_capability_specific,c_restriction_possession_general_quality_specific,restriction_possession_general_quantity,restriction_possession_general_quantity_specific,c_restriction_possession_general_quantity_specific,restriction_possession_general_quantity_type,restriction_possession_general_quantity_type_other,c_restriction_possession_general_quantity_type,restriction_possession_general_item_counting,c_restriction_possession_general_item_counting,restriction_possession_general_item_counting_point,c_restriction_possession_general_item_counting_point,restriction_possession_non_deployed,c_restriction_possession_non_deployed,restriction_possession_non_deployed_party,restriction_possession_non_deployed_party_specific,c_restriction_possession_non_deployed_party_specific,restriction_possession_non_deployed_location,restriction_possession_non_deployed_location_specific,c_restriction_possession_non_deployed_location_specific,restriction_possession_non_deployed_facility,restriction_possession_non_deployed_facility_specific,c_restriction_possession_non_deployed_facility_specific,restriction_possession_non_deployed_quality,restriction_possession_non_deployed_quality_practice,restriction_possession_non_deployed_quality_practice_specified,restriction_possession_non_deployed_quality_capability,restriction_possession_non_deployed_quality_capability_specific,c_restriction_possession_non_deployed_quality_specific,restriction_possession_non_deployed_quantity,restriction_possession_non_deployed_quantity_specific,c_restriction_possession_non_deployed_quantity_specific,restriction_possession_non_deployed_quantity_type,restriction_possession_non_deployed_quantity_type_other,c_restriction_possession_non_deployed_quantity_type,restriction_possession_non_deployed_item_counting,c_restriction_possession_non_deployed_item_counting,restriction_possession_non_deployed_item_counting_point,c_restriction_possession_non_deployed_item_counting_point,restriction_possession_deployed,c_restriction_possession_deployed,restriction_possession_deployed_party,restriction_possession_deployed_party_specific,c_restriction_possession_deployed_party_specific,restriction_possession_deployed_location,restriction_possession_deployed_location_specific,c_restriction_possession_deployed_location_specific,restriction_possession_deployed_facility,restriction_possession_deployed_facility_specific,c_restriction_possession_deployed_facility_specific,restriction_possession_deployed_quality,restriction_possession_deployed_quality_practice,restriction_possession_deployed_quality_practice_specified,restriction_possession_deployed_quality_capability,restriction_possession_deployed_quality_capability_specific,c_restriction_possession_deployed_quality_specific,restriction_possession_deployed_quantity,restriction_possession_deployed_quantity_specific,c_restriction_possession_deployed_quantity_specific,restriction_possession_deployed_quantity_type,restriction_possession_deployed_quantity_type_other,c_restriction_possession_deployed_quantity_type,restriction_possession_deployed_item_counting,c_restriction_possession_deployed_item_counting,restriction_possession_deployed_item_counting_point,c_restriction_possession_deployed_item_counting_point,restriction_transfer,c_restriction_transfer,restriction_transfer_party,restriction_transfer_party_specific,c_restriction_transfer_party_specific,restriction_transfer_location,restriction_transfer_location_specific,c_restriction_transfer_location_specific,restriction_transfer_facility,restriction_transfer_facility_specific,c_restriction_transfer_facility_specific,restriction_transfer_quality,restriction_transfer_quality_practice,restriction_transfer_quality_practice_specified,restriction_transfer_quality_capability,restriction_transfer_quality_capability_specific,c_restriction_transfer_quality_specific,restriction_transfer_quantity,restriction_transfer_quantity_specific,c_restriction_transfer_quantity_specific,restriction_transfer_quantity_type,restriction_transfer_quantity_type_other,c_restriction_transfer_quantity_type,restriction_transfer_item_counting,c_restriction_transfer_item_counting,restriction_transfer_item_counting_point,c_restriction_transfer_item_counting_point,restriction_use,c_restriction_use,restriction_use_party,restriction_use_party_specific,c_restriction_use_party_specific,restriction_use_location,restriction_use_location_specific,c_restriction_use_location_specific,restriction_use_facility,restriction_use_facility_specific,c_restriction_use_facility_specific,restriction_use_quality,restriction_use_quality_practice,restriction_use_quality_practice_specified,restriction_use_quality_capability,restriction_use_quality_capability_specific,c_restriction_use_quality_specific,restriction_use_quantity,restriction_use_quantity_specific,c_restriction_use_quanity_specific,restriction_use_quantity_type,restriction_use_quantity_type_other,c_restriction_use_quantity_type,restriction_use_item_counting,c_restriction_use_item_counting,restriction_use_item_counting_point,c_restriction_use_item_counting_point,restriction_disposal,c_restriction_disposal,restriction_disposal_party,restriction_disposal_party_specific,c_restriction_disposal_party_specific,restriction_disposal_location,restriction_disposal_location_specific,c_restriction_disposal_location_specific,restriction_disposal_facility,restriction_disposal_facility_specific,c_restriction_disposal_facility_specific,restriction_disposal_quality,restriction_disposal_quality_practice,restriction_disposal_quality_practice_specified,restriction_disposal_quality_capability,restriction_disposal_quality_capability_specific,c_restriction_disposal_quality_specific,restriction_disposal_quantity,restriction_disposal_quantity_specific,c_restriction_disposal_quanity_specific,restriction_disposal_quantity_type,restriction_disaposal_quantity_type_other,c_restriction_disposal_quantity_type,restriction_disaposal_item_counting_point,c_restriction_disaposal_item_counting_point,restriction_disposal_item_counting_point,c_restriction_disposal_item_counting_point,facility_destruction,facility_destruction_specified,c_facility_destriction,facility_conversion,facility_conversion_specified,c_facility_conversion,facility_use,facility_use_specified,c_facility_use,eliminitation,elimination_procedure,c_elimination,point_of_elimination,c_point_of_elimination,conversion,conversion_procedure,c_conversion_procedure,point_of_conversion,c_point_of_conversion,modernization,modernization_other,c_modernization,obligations_timeframe_type,timeframe_set_time,timeframe_other,c_obligations_timeframe,timeframe_phases,c_timeframe_phases,phases_number,c_phases,timeframe_obligations_extention,timeframe_obligations_extention_specified,c_timeframe_obligations_extention_specified,excepetions,excepetions_specified,c_excpetions,Unnamed: 475,Unnamed: 476,Unnamed: 477,Unnamed: 478,Unnamed: 479,Unnamed: 480,Unnamed: 481,Unnamed: 482,Unnamed: 483,Unnamed: 484,Unnamed: 485,Unnamed: 486,Unnamed: 487,Unnamed: 488,Unnamed: 489,Unnamed: 490,Unnamed: 491,Unnamed: 492,Unnamed: 493,Unnamed: 494,Unnamed: 495,Unnamed: 496,Unnamed: 497,Unnamed: 498,Unnamed: 499,Unnamed: 500,Unnamed: 501
251,140206,A,1.0,1.0,ABM Interceptor Missiles,NaN,"Interceptor missile, as used in the First Agre...",Common Understandings Related To The First Agr...,NaN,NaN,0.0,0,NaN,0,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,0.0,NaN,0.0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,0.0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,NaN,0,0.0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,0.0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,0.0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,0.0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,1,Ibid. Article IX: To assure the viability and ...,1,0,NaN,0,NaN,0,NaN,1,NaN,0,NaN,NaN,0,NaN,0,0.0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,0.0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,0,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Ibid. Article 1: 1 Each Party shall be limited...,0,NaN,NaN,1,Location-specific Possession-restriction: rest...,Ibid. Article IX: To assure the viability and ...,1,Location-Facility-Quantity-specific Possession...,Ibid. Article 1: 1 Each Party shall be limited...,0.0,NaN,NaN,NaN,NaN,NaN,1,Location-Facility-Quantity-specific Possession...,Ibid. Article III: The rights and obligations ...,0.0,NaN,Ibid. Article III: The rights and obligations ...,NaN,NaN,NaN,NaN,0,NaN,0.0,NaN,NaN,0.0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,ibid. Article II:3: Dismantling or destruction...,NaN,NaN,0,NaN,NaN,NaN,NaN,0.0,NaN,Ibid. Article 2: Any replacement of ABM system...,2.0,NaN,Within the shortest possible agreed period of ...,Ibid. Article IIII: The rights and obligations...,0.0,NaN,NaN,NaN,2.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Select only the binary columns and remove those starting with c_

### Life cyle stages filter (rough):

In [92]:
cols_to_keep = [
    # Identifiers
    'item_type', 'item',

    # Lifecycle stages - ban flags
    'ban_development',
    'ban_testing',
    'ban_production',
    'ban_acquisition',
    'ban_possession',
    'ban_station',
    'ban_transfer',
    'ban_use',
    'ban_disposal',

    # Lifecycle stages - restriction flags
    'restriction_development',
    'testing_restriction',       # note: inconsistent naming in the dataset
    'restriction_production',
    'restriction_acquisition',
    'restriction_possession',
    'restriction_transfer',
    'restriction_use',
    'restriction_disposal',

    # End-of-life stages (no ban/restriction equivalents)
    'eliminitation',             # note: typo in the dataset
    'conversion',
    'modernization',
    'facility_destruction',
]

weapons_lifecycle_filtered_df = weapons_nosummary_df[cols_to_keep]
weapons_lifecycle_filtered_df.sample(10)

,item_type,item,ban_development,ban_testing,ban_production,ban_acquisition,ban_possession,ban_station,ban_transfer,ban_use,ban_disposal,restriction_development,testing_restriction,restriction_production,restriction_acquisition,restriction_possession,restriction_transfer,restriction_use,restriction_disposal,eliminitation,conversion,modernization,facility_destruction
291,1.0,Heavy Bombers,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,1,0,0.0,NaN
430,0.0,Armoured Combat Vehicles,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0
94,3.0,Fissile Material,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,2.0,NaN
269,1.0,SLBM Launchers,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,1,0,1,1,2.0,NaN
140,1.0,Nuclear Weapons,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,2.0,NaN
302,1.0,Heavy ICBMs,0,0,0,0,0,0,0,0,0,1,1,1,0,1,0,0,0,0,0,0.0,NaN
9,3.0,Nuclear Material,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,2.0,NaN
404,1.0,Fortification,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0.0,0.0
208,1.0,Light Surface Vessels,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,2.0,NaN
71,3.0,Radioactive Waste,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,2.0,NaN

### Test correlations:

In [93]:
# Separate ban and restriction columns
ban_cols = [c for c in weapons_lifecycle_filtered_df.columns if c.startswith('ban_')]
restriction_cols = [c for c in weapons_lifecycle_filtered_df.columns if 'restriction' in c]

# Correlation between every ban col vs every restriction col
corr_matrix = weapons_lifecycle_filtered_df[ban_cols + restriction_cols].corr()

# Slice to only show ban vs restriction (not ban vs ban or restriction vs restriction)
corr_ban_vs_restriction = corr_matrix.loc[ban_cols, restriction_cols]
print(corr_ban_vs_restriction)

                 restriction_development  testing_restriction  \
ban_development                -0.084688            -0.087420
ban_testing                    -0.098284            -0.101454
ban_production                 -0.112421            -0.085467
ban_acquisition                -0.130349            -0.134554
ban_possession                       NaN                  NaN
ban_station                    -0.053127            -0.054841
ban_transfer                   -0.015468            -0.021429
ban_use                        -0.086724            -0.089521
ban_disposal                   -0.046718            -0.048224

                 restriction_production  restriction_acquisition  \
ban_development               -0.118599                -0.086061
ban_testing                   -0.137638                -0.099876
ban_production                -0.132952                -0.114242
ban_acquisition                0.123815                -0.132462
ban_possession                      NaN                      NaN
ban_station                   -0.074400                -0.053988
ban_transfer                  -0.130264                -0.112509
ban_use                       -0.121449                -0.088129
ban_disposal                  -0.065424                -0.047474

                 restriction_possession  restriction_transfer  \
ban_development               -0.146927             -0.111468
ban_testing                   -0.177647             -0.129362
ban_production                -0.208745             -0.147969
ban_acquisition               -0.265343             -0.011893
ban_possession                      NaN                   NaN
ban_station                   -0.108148             -0.069927
ban_transfer                  -0.021911             -0.145724
ban_use                       -0.026864             -0.114146
ban_disposal                  -0.095100             -0.005430

                 restriction_use  restriction_disposal
ban_development        -0.112667             -0.019576
ban_testing            -0.045973             -0.022718
ban_production         -0.124225             -0.025986
ban_acquisition        -0.150769             -0.030130
ban_possession               NaN                   NaN
ban_station            -0.021456             -0.012280
ban_transfer           -0.121647             -0.025592
ban_use                -0.115375             -0.020046
ban_disposal           -0.006501             -0.010799

### Flattened into a ranked list:

In [96]:
# Stack matrix into a series and sort
corr_ranked = (
    corr_ban_vs_restriction
    .stack()
    .reset_index()
    .rename(columns={'level_0': 'ban', 'level_1': 'restriction', 0: 'correlation'})
    .sort_values('correlation', ascending=False)
)

print(corr_ranked.head(40))

                ban              restriction  correlation
26  ban_acquisition   restriction_production     0.123815
61     ban_disposal     restriction_transfer    -0.005430
62     ban_disposal          restriction_use    -0.006501
63     ban_disposal     restriction_disposal    -0.010799
29  ban_acquisition     restriction_transfer    -0.011893
39      ban_station     restriction_disposal    -0.012280
40     ban_transfer  restriction_development    -0.015468
7   ban_development     restriction_disposal    -0.019576
55          ban_use     restriction_disposal    -0.020046
41     ban_transfer      testing_restriction    -0.021429
38      ban_station          restriction_use    -0.021456
44     ban_transfer   restriction_possession    -0.021911
15      ban_testing     restriction_disposal    -0.022718
47     ban_transfer     restriction_disposal    -0.025592
23   ban_production     restriction_disposal    -0.025986
52          ban_use   restriction_possession    -0.026864
31  ban_acquisition     restriction_disposal    -0.030130
14      ban_testing          restriction_use    -0.045973
56     ban_disposal  restriction_development    -0.046718
59     ban_disposal  restriction_acquisition    -0.047474
57     ban_disposal      testing_restriction    -0.048224
32      ban_station  restriction_development    -0.053127
35      ban_station  restriction_acquisition    -0.053988
33      ban_station      testing_restriction    -0.054841
58     ban_disposal   restriction_production    -0.065424
37      ban_station     restriction_transfer    -0.069927
34      ban_station   restriction_production    -0.074400
0   ban_development  restriction_development    -0.084688
17   ban_production      testing_restriction    -0.085467
3   ban_development  restriction_acquisition    -0.086061
48          ban_use  restriction_development    -0.086724
1   ban_development      testing_restriction    -0.087420
51          ban_use  restriction_acquisition    -0.088129
49          ban_use      testing_restriction    -0.089521
60     ban_disposal   restriction_possession    -0.095100
8       ban_testing  restriction_development    -0.098284
11      ban_testing  restriction_acquisition    -0.099876
9       ban_testing      testing_restriction    -0.101454
36      ban_station   restriction_possession    -0.108148
5   ban_development     restriction_transfer    -0.111468

### Pearson and Spearman

In [ ]:
# Pearson - default, fine for binary
weapons_lifecycle_filtered_df[ban_cols + restriction_cols].corr(method='pearson')

,ban_development,ban_testing,ban_production,ban_acquisition,ban_possession,ban_station,ban_transfer,ban_use,ban_disposal,restriction_development,testing_restriction,restriction_production,restriction_acquisition,restriction_possession,restriction_transfer,restriction_use,restriction_disposal
ban_development,1.000000,0.477423,0.561934,0.239179,NaN,0.181143,0.261266,0.359027,-0.036888,-0.084688,-0.087420,-0.118599,-0.086061,-0.146927,-0.111468,-0.112667,-0.019576
ban_testing,0.477423,1.000000,0.604658,0.151624,NaN,0.344140,0.000875,0.129629,-0.042810,-0.098284,-0.101454,-0.137638,-0.099876,-0.177647,-0.129362,-0.045973,-0.022718
ban_production,0.561934,0.604658,1.000000,0.349413,NaN,0.355185,0.220332,0.359006,-0.048967,-0.112421,-0.085467,-0.132952,-0.114242,-0.208745,-0.147969,-0.124225,-0.025986
ban_acquisition,0.239179,0.151624,0.349413,1.000000,NaN,0.250195,0.330077,0.229696,-0.056777,-0.130349,-0.134554,0.123815,-0.132462,-0.265343,-0.011893,-0.150769,-0.030130
ban_possession,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ban_station,0.181143,0.344140,0.355185,0.250195,NaN,1.000000,0.004570,0.102724,-0.023141,-0.053127,-0.054841,-0.074400,-0.053988,-0.108148,-0.069927,-0.021456,-0.012280
ban_transfer,0.261266,0.000875,0.220332,0.330077,NaN,0.004570,1.000000,0.176122,-0.048224,-0.015468,-0.021429,-0.130264,-0.112509,-0.021911,-0.145724,-0.121647,-0.025592
ban_use,0.359027,0.129629,0.359006,0.229696,NaN,0.102724,0.176122,1.000000,-0.037774,-0.086724,-0.089521,-0.121449,-0.088129,-0.026864,-0.114146,-0.115375,-0.020046
ban_disposal,-0.036888,-0.042810,-0.048967,-0.056777,NaN,-0.023141,-0.048224,-0.037774,1.000000,-0.046718,-0.048224,-0.065424,-0.047474,-0.095100,-0.005430,-0.006501,-0.010799
restriction_development,-0.084688,-0.098284,-0.112421,-0.130349,NaN,-0.053127,-0.015468,-0.086724,-0.046718,1.000000,0.270274,0.053157,-0.076845,0.052978,-0.035179,-0.037471,-0.024792
testing_restriction,-0.087420,-0.101454,-0.085467,-0.134554,NaN,-0.054841,-0.021429,-0.089521,-0.048224,0.270274,1.000000,0.191902,-0.081167,0.222244,-0.042392,-0.147292,-0.025592
restriction_production,-0.118599,-0.137638,-0.132952,0.123815,NaN,-0.074400,-0.130264,-0.121449,-0.065424,0.053157,0.191902,1.000000,0.273958,0.101501,0.174599,-0.076631,0.065169
restriction_acquisition,-0.086061,-0.099876,-0.114242,-0.132462,NaN,-0.053988,-0.112509,-0.088129,-0.047474,-0.076845,-0.081167,0.273958,1.000000,-0.118859,0.484330,-0.067100,0.101135
restriction_possession,-0.146927,-0.177647,-0.208745,-0.265343,NaN,-0.108148,-0.021911,-0.026864,-0.095100,0.052978,0.222244,0.101501,-0.118859,1.000000,-0.100580,-0.071319,0.031542
restriction_transfer,-0.111468,-0.129362,-0.147969,-0.011893,NaN,-0.069927,-0.145724,-0.114146,-0.005430,-0.035179,-0.042392,0.174599,0.484330,-0.100580,1.000000,0.111832,0.071493
restriction_use,-0.112667,-0.045973,-0.124225,-0.150769,NaN,-0.021456,-0.121647,-0.115375,-0.006501,-0.037471,-0.147292,-0.076631,-0.067100,-0.071319,0.111832,1.000000,-0.032983
restriction_disposal,-0.019576,-0.022718,-0.025986,-0.030130,NaN,-0.012280,-0.025592,-0.020046,-0.010799,-0.024792,-0.025592,0.065169,0.101135,0.031542,0.071493,-0.032983,1.000000

# Spearman - better for ordinal/binary data, more robust

In [100]:
weapons_lifecycle_filtered_df[ban_cols + restriction_cols].corr(method='spearman')

,ban_development,ban_testing,ban_production,ban_acquisition,ban_possession,ban_station,ban_transfer,ban_use,ban_disposal,restriction_development,testing_restriction,restriction_production,restriction_acquisition,restriction_possession,restriction_transfer,restriction_use,restriction_disposal
ban_development,1.000000,0.477423,0.561934,0.239179,NaN,0.181143,0.261266,0.359027,-0.036888,-0.084688,-0.087420,-0.118599,-0.086061,-0.146927,-0.111468,-0.112667,-0.019576
ban_testing,0.477423,1.000000,0.604658,0.151624,NaN,0.344140,0.000875,0.129629,-0.042810,-0.098284,-0.101454,-0.137638,-0.099876,-0.177647,-0.129362,-0.045973,-0.022718
ban_production,0.561934,0.604658,1.000000,0.349413,NaN,0.355185,0.220332,0.359006,-0.048967,-0.112421,-0.085467,-0.132952,-0.114242,-0.208745,-0.147969,-0.124225,-0.025986
ban_acquisition,0.239179,0.151624,0.349413,1.000000,NaN,0.250195,0.330077,0.229696,-0.056777,-0.130349,-0.134554,0.123815,-0.132462,-0.265343,-0.011893,-0.150769,-0.030130
ban_possession,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ban_station,0.181143,0.344140,0.355185,0.250195,NaN,1.000000,0.004570,0.102724,-0.023141,-0.053127,-0.054841,-0.074400,-0.053988,-0.108148,-0.069927,-0.021456,-0.012280
ban_transfer,0.261266,0.000875,0.220332,0.330077,NaN,0.004570,1.000000,0.176122,-0.048224,-0.015468,-0.021429,-0.130264,-0.112509,-0.021911,-0.145724,-0.121647,-0.025592
ban_use,0.359027,0.129629,0.359006,0.229696,NaN,0.102724,0.176122,1.000000,-0.037774,-0.086724,-0.089521,-0.121449,-0.088129,-0.026864,-0.114146,-0.115375,-0.020046
ban_disposal,-0.036888,-0.042810,-0.048967,-0.056777,NaN,-0.023141,-0.048224,-0.037774,1.000000,-0.046718,-0.048224,-0.065424,-0.047474,-0.095100,-0.005430,-0.006501,-0.010799
restriction_development,-0.084688,-0.098284,-0.112421,-0.130349,NaN,-0.053127,-0.015468,-0.086724,-0.046718,1.000000,0.270274,0.053157,-0.076845,0.052978,-0.035179,-0.037471,-0.024792
testing_restriction,-0.087420,-0.101454,-0.085467,-0.134554,NaN,-0.054841,-0.021429,-0.089521,-0.048224,0.270274,1.000000,0.191902,-0.081167,0.222244,-0.042392,-0.147292,-0.025592
restriction_production,-0.118599,-0.137638,-0.132952,0.123815,NaN,-0.074400,-0.130264,-0.121449,-0.065424,0.053157,0.191902,1.000000,0.273958,0.101501,0.174599,-0.076631,0.065169
restriction_acquisition,-0.086061,-0.099876,-0.114242,-0.132462,NaN,-0.053988,-0.112509,-0.088129,-0.047474,-0.076845,-0.081167,0.273958,1.000000,-0.118859,0.484330,-0.067100,0.101135
restriction_possession,-0.146927,-0.177647,-0.208745,-0.265343,NaN,-0.108148,-0.021911,-0.026864,-0.095100,0.052978,0.222244,0.101501,-0.118859,1.000000,-0.100580,-0.071319,0.031542
restriction_transfer,-0.111468,-0.129362,-0.147969,-0.011893,NaN,-0.069927,-0.145724,-0.114146,-0.005430,-0.035179,-0.042392,0.174599,0.484330,-0.100580,1.000000,0.111832,0.071493
restriction_use,-0.112667,-0.045973,-0.124225,-0.150769,NaN,-0.021456,-0.121647,-0.115375,-0.006501,-0.037471,-0.147292,-0.076631,-0.067100,-0.071319,0.111832,1.000000,-0.032983
restriction_disposal,-0.019576,-0.022718,-0.025986,-0.030130,NaN,-0.012280,-0.025592,-0.020046,-0.010799,-0.024792,-0.025592,0.065169,0.101135,0.031542,0.071493,-0.032983,1.000000