# Exploratory Data Analysis
This notebook is used to explore the initial dataset and see what we have to work with

In [3]:
import pandas as pd
pd.options.display.max_columns = None

data_df = pd.read_csv('data/amcdata_weapons_facilities_V2.csv', encoding='latin-1')

In [9]:
data_groupby_df = data_df.groupby(['ban_development']).count()
data_groupby_df.head(5)

,agreement_id,Item_letter,Item_number,item_type,item,facility,weapon_item_definition,c_weapon_item_definition,subcategory,subcategory_main,summary_category,c_ban_development,ban_development_execution_type,ban_development_assistance_grant,c_ban_development_assistance_grant,ban_development_assistance_gain,c_ban_development_assistance_gain,ban_development_permission,c_ban_development_permission,ban_development_execution,c_ban_development_execution,ban_development_party,ban_development_party_specific,c_ban_development_party_specific,ban_testing,c_testing_,ban_testing_execution_type,ban_testing_assistance_grant,c_ban_testing_assistance_grant,ban_testing_assistance_gain,c_ban_tesing_assistance_gain,ban_testing_permission,c_ban_testing_permission,ban_testing_execution,c_ban_testing_execution,ban_testing_party,ban_testing_party_specific,c_ban_testing_party_specific,ban_production,c_ban_production,ban_production_execution_type,ban_production_assistance_grant,c_ban_priduction_assistance_grant,ban_production_assistance_gain,c_ban_production_assistance_gain,ban_production_permission,c_ban_production_permission,ban_production_execution,c_ban_production_execution,ban_production_party,ban_production_party_specific,c_ban_production_party_specific,ban_acquisition,c_ban_acquisition,ban_acquisition_execution_type,ban_acquisition_assistance_grant,c_ban_acquisition_assistance_grant,ban_acquisition_assistance_gain,c_ban_acquisition_assistance_gain,ban_acquisition_permission,c_ban_acquisition_permission,ban_acquisition_execution,c_ban_acquisition_execution,ban_acquisition_party,ban_acquisition_party_specific,c_ban_acquisition_party_specific,ban_possession,c_ban_possession,ban_possession_general,c_ban_possession_general,ban_possession_general_execution_type,ban_possession_general_assistance_grant,c_ban_possession_general_assistance_grant,ban_possession_general_assistance_gain,c_ban_possession_general_assistance_gain,ban_possession_general_permission,c_ban_possession_general_permission,ban_possession_general_execution,c_ban_possession_general_execution,ban_possession_party,ban_possession_party_specific,c_ban_possession_party_specific,ban_possession_non_deployed,c_ban_possession_non_deployed,ban_possession_non_deployed_execution_type,ban_possession_non_deployed_assistance_grant,c_ban_possession_non_deployed_assistance_grant,ban_possession_non_deployed_assistance_gain,c_ban_possession_non_deployed_assistance_gain,ban_possession_non_deployed_permission,c_ban_possession_non_deployed_permission,ban_possession_non_deployed_execution,c_ban_possession_non_deployed_execution,ban_possession_non_deployed_party,ban_possession_non_deployed_party_specific,c_ban_possession_non_deployed_party_specific,ban_possession_deployed,c_ban_possession_deployed,ban_possession_deployed_execution_type,ban_possession_deployed_assistance_grant,c_ban_possession_deployed_assistance_grant,ban_possession_deployed_assistance_gain,c_ban_possession_deployed_assistance_gain,ban_possession_deployed_permission,c_ban_possession_deployed_permission,ban_possession_deployed_execution,c_ban_possession_deployed_execution,ban_possession_deployed_party,ban_possession_deployed_party_specific,c_ban_possession_deployed_party_specific,ban_station,c_ban_station,ban_station_execution_type,ban_station_assistance_grant,c_ban_station_assistance_grant,ban_station_assistance_gain,c_ban_station_assistance_gain,ban_station_permission,c_ban_station_permission,ban_station_execution,c_ban_station_execution,ban_station_party,ban_station_party_specific,c_ban_station_party_specific,ban_transfer,c_ban_transfer,ban_transfer_execution_type,ban_transfer_assistance_grant,c_ban_transfer_assistance_grant,ban_transfer_assistance_gain,c_ban_transfer_assistance_gain,ban_transfer_permission,c_ban_transfer_permission,ban_transfer_execution,c_ban_transfer_execution,ban_transfer_party,ban_transfer_party_specific,c_ban_transfer_party_specific,ban_use,c_ban_use,ban_use_execution_type,ban_use_assistance_grant,c_ban_use_assistance_grant,ban_use_assistance_gain,c_ban_use_assistance_gain,ban_use_permission,c_ban_use_permission,ban_use_execution,c_ban_use_execution,ban_use_party,ban_use_party_specific,c_ban_use_party_specific,ban_disposal,c_ban_disposal,ban_disposal_interaction_type,ban_disposal_assistance_grant,c_ban_disposal_assistance_grant,ban_disposal_assistance_gain,c_ban_disposal_assistance_gain,ban_disposal_permission,c_ban_disposal_permission,ban_disposal_execution,c_ban_disposal_execution,ban_disposal_party,ban_disposal_party_specific,c_ban_disposal_party_specific,restriction_development,c_restriction_development,restriction_development_party,restriction_development_party_specific,c_restriction_development_party_specific,restriction_development_location,restriction_development_location_specific,c_restriction_development_location_specific,restriction_development_facility,restriction_development_facility_specific,c_restriction_development_facility_specific,restriction_development_quality,restriction_development_quality_practice,restriction_development_quality_practice_specified,restriction_development_quality_capability,restriction_development_quality_capability_specific,c_restriction_development_quality_specific,restriction_development_quantity,restriction_development_quantity_specific,c_restriction_development_quantity_specific,restriction_development_quantity_type,restriction_development_quantity_type_other,c_restriction_development_quantity_type,restriction_development_item_counting,c_restriction_development_item_counting,restriction_development_item_counting_point,c_restriction_development_item_counting_point,testing_restriction,c_testing_restriction,restriction_testing_party,restriction_testing_party_specific,c_restriction_testing_party_specific,restriction_testing_location,restriction_testing_location_specific,c_restriction_testing_location_specific,restriction_testing_facility,restriction_testing_facility_specific,c_restriction_testing_facility_specific,restriction_testing_quality,restriction_testing_quality_practice,restriction_testing_quality_practice_specified,restriction_testing_quality_capability,restriction_testing_quality_capability_specific,c_restriction_testing_quality_specific,restriction_testing_quantity,restriction_testing_quantity_specific,c_restriction_testing_quantity_specific,restriction_testing_quantity_type,restriction_testing_quantity_type_other,c_restriction_testing_quantity_type,restriction_testing_item_counting,c_restriction_testing_item_counting,restriction_testing_item_counting_point,c_restriction_testing_item_counting_point,restriction_production,c_restriction_production,restriction_production_party,restriction_production_party_specific,c_restriction_production_party_specific,restriction_production_location,restriction_production_location_specific,c_restriction_production_location_specific,restriction_production_facility,restriction_production_facility_specific,c_restriction_production_facility_specific,restriction_production_quality,restriction_production_quality_practice,restriction_production_quality_practice_specified,restriction_production_quality_capability,restriction_production_quality_capability_specific,c_restriction_production_quality_specific,restriction_production_quantity,restriction_production_quantity_specific,c_restriction_production_quantity_specific,restriction_production_quantity_type,restriction_production_quantity_type_other,c_restriction_production_quantity_type,restriction_production_item_counting,c_restriction_production_item_counting,restriction_production_item_counting_point,c_restriction_production_item_counting_point,restriction_acquisition,c_restriction_acquisition,restriction_acquisition_party,restriction_acquisition_party_specific,c_restriction_acquisition_party_specific,restriction_acquisition_location,restriction_acquisition_location_specific,c_restriction_acquisition_location_specific,restriction_acquisition_facility,restriction_acquisition_facility_specific,c_restriction_acquisition_facility_specific,restriction_acquisition_quality,restriction_acquisition_quality_practice,restriction_acquisition_quality_practice_specified,restriction_acquisition_quality_capability,restriction_acquisition_quality_capability_specific,c_restriction_acquisition_quality_specific,restriction_acquisition_quantity,restriction_acquisition_quantity_specific,c_restriction_acquisition_quantity_specific,restriction_acquisition_quantity_type,restriction_acquisition_quantity_type_other,c_restriction_acquisition_quantity_type,restriction_acquisition_item_counting,c_restriction_acquisition_item_counting,restriction_acquisition_item_counting_point,c_restriction_acquisition_item_counting_point,restriction_possession,c_restriction_possession,restriction_possession_general,c_restriction_possession_general,restriction_possession_general_party,restriction_possession_general_party_specific,c_restriction_possession_general_party_specific,restriction_possession_general_location,restriction_possession_general_location_specific,c_restriction_possession_general_location_specific,restriction_possession_general_facility,restriction_possession_general_facility_specific,c_restriction_possession_general_facility_specific,restriction_possession_general_quality,restriction_possession_general_quality_practice,restriction_possession_general_quality_practice_specified,restriction_possession_general_quality_capability,restriction_possession_general_quality_capability_specific,c_restriction_possession_general_quality_specific,restriction_possession_general_quantity,restriction_possession_general_quantity_specific,c_restriction_possession_general_quantity_specific,restriction_possession_general_quantity_type,restriction_possession_general_quantity_type_other,c_restriction_possession_general_quantity_type,restriction_possession_general_item_counting,c_restriction_possession_general_item_counting,restriction_possession_general_item_counting_point,c_restriction_possession_general_item_counting_point,restriction_possession_non_deployed,c_restriction_possession_non_deployed,restriction_possession_non_deployed_party,restriction_possession_non_deployed_party_specific,c_restriction_possession_non_deployed_party_specific,restriction_possession_non_deployed_location,restriction_possession_non_deployed_location_specific,c_restriction_possession_non_deployed_location_specific,restriction_possession_non_deployed_facility,restriction_possession_non_deployed_facility_specific,c_restriction_possession_non_deployed_facility_specific,restriction_possession_non_deployed_quality,restriction_possession_non_deployed_quality_practice,restriction_possession_non_deployed_quality_practice_specified,restriction_possession_non_deployed_quality_capability,restriction_possession_non_deployed_quality_capability_specific,c_restriction_possession_non_deployed_quality_specific,restriction_possession_non_deployed_quantity,restriction_possession_non_deployed_quantity_specific,c_restriction_possession_non_deployed_quantity_specific,restriction_possession_non_deployed_quantity_type,restriction_possession_non_deployed_quantity_type_other,c_restriction_possession_non_deployed_quantity_type,restriction_possession_non_deployed_item_counting,c_restriction_possession_non_deployed_item_counting,restriction_possession_non_deployed_item_counting_point,c_restriction_possession_non_deployed_item_counting_point,restriction_possession_deployed,c_restriction_possession_deployed,restriction_possession_deployed_party,restriction_possession_deployed_party_specific,c_restriction_possession_deployed_party_specific,restriction_possession_deployed_location,restriction_possession_deployed_location_specific,c_restriction_possession_deployed_location_specific,restriction_possession_deployed_facility,restriction_possession_deployed_facility_specific,c_restriction_possession_deployed_facility_specific,restriction_possession_deployed_quality,restriction_possession_deployed_quality_practice,restriction_possession_deployed_quality_practice_specified,restriction_possession_deployed_quality_capability,restriction_possession_deployed_quality_capability_specific,c_restriction_possession_deployed_quality_specific,restriction_possession_deployed_quantity,restriction_possession_deployed_quantity_specific,c_restriction_possession_deployed_quantity_specific,restriction_possession_deployed_quantity_type,restriction_possession_deployed_quantity_type_other,c_restriction_possession_deployed_quantity_type,restriction_possession_deployed_item_counting,c_restriction_possession_deployed_item_counting,restriction_possession_deployed_item_counting_point,c_restriction_possession_deployed_item_counting_point,restriction_transfer,c_restriction_transfer,restriction_transfer_party,restriction_transfer_party_specific,c_restriction_transfer_party_specific,restriction_transfer_location,restriction_transfer_location_specific,c_restriction_transfer_location_specific,restriction_transfer_facility,restriction_transfer_facility_specific,c_restriction_transfer_facility_specific,restriction_transfer_quality,restriction_transfer_quality_practice,restriction_transfer_quality_practice_specified,restriction_transfer_quality_capability,restriction_transfer_quality_capability_specific,c_restriction_transfer_quality_specific,restriction_transfer_quantity,restriction_transfer_quantity_specific,c_restriction_transfer_quantity_specific,restriction_transfer_quantity_type,restriction_transfer_quantity_type_other,c_restriction_transfer_quantity_type,restriction_transfer_item_counting,c_restriction_transfer_item_counting,restriction_transfer_item_counting_point,c_restriction_transfer_item_counting_point,restriction_use,c_restriction_use,restriction_use_party,restriction_use_party_specific,c_restriction_use_party_specific,restriction_use_location,restriction_use_location_specific,c_restriction_use_location_specific,restriction_use_facility,restriction_use_facility_specific,c_restriction_use_facility_specific,restriction_use_quality,restriction_use_quality_practice,restriction_use_quality_practice_specified,restriction_use_quality_capability,restriction_use_quality_capability_specific,c_restriction_use_quality_specific,restriction_use_quantity,restriction_use_quantity_specific,c_restriction_use_quanity_specific,restriction_use_quantity_type,restriction_use_quantity_type_other,c_restriction_use_quantity_type,restriction_use_item_counting,c_restriction_use_item_counting,restriction_use_item_counting_point,c_restriction_use_item_counting_point,restriction_disposal,c_restriction_disposal,restriction_disposal_party,restriction_disposal_party_specific,c_restriction_disposal_party_specific,restriction_disposal_location,restriction_disposal_location_specific,c_restriction_disposal_location_specific,restriction_disposal_facility,restriction_disposal_facility_specific,c_restriction_disposal_facility_specific,restriction_disposal_quality,restriction_disposal_quality_practice,restriction_disposal_quality_practice_specified,restriction_disposal_quality_capability,restriction_disposal_quality_capability_specific,c_restriction_disposal_quality_specific,restriction_disposal_quantity,restriction_disposal_quantity_specific,c_restriction_disposal_quanity_specific,restriction_disposal_quantity_type,restriction_disaposal_quantity_type_other,c_restriction_disposal_quantity_type,restriction_disaposal_item_counting_point,c_restriction_disaposal_item_counting_point,restriction_disposal_item_counting_point,c_restriction_disposal_item_counting_point,facility_destruction,facility_destruction_specified,c_facility_destriction,facility_conversion,facility_conversion_specified,c_facility_conversion,facility_use,facility_use_specified,c_facility_use,eliminitation,elimination_procedure,c_elimination,point_of_elimination,c_point_of_elimination,conversion,conversion_procedure,c_conversion_procedure,point_of_conversion,c_point_of_conversion,modernization,modernization_other,c_modernization,obligations_timeframe_type,timeframe_set_time,timeframe_other,c_obligations_timeframe,timeframe_phases,c_timeframe_phases,phases_number,c_phases,timeframe_obligations_extention,timeframe_obligations_extention_specified,c_timeframe_obligations_extention_specified,excepetions,excepetions_specified,c_excpetions,Unnamed: 475,Unnamed: 476,Unnamed: 477,Unnamed: 478,Unnamed: 479,Unnamed: 480,Unnamed: 481,Unnamed: 482,Unnamed: 483,Unnamed: 484,Unnamed: 485,Unnamed: 486,Unnamed: 487,Unnamed: 488,Unnamed: 489,Unnamed: 490,Unnamed: 491,Unnamed: 492,Unnamed: 493,Unnamed: 494,Unnamed: 495,Unnamed: 496,Unnamed: 497,Unnamed: 498,Unnamed: 499,Unnamed: 500,Unnamed: 501
ban_development,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0,400,329,329,397,382,19,243,106,0,0,319,0,400,400,0,400,0,400,0,400,0,400,0,0,400,24,400,400,6,400,2,400,4,400,4,400,0,0,400,28,400,319,87,319,6,400,4,400,4,400,3,3,400,41,400,319,2,400,2,400,0,400,0,400,25,2,400,0,400,32,400,319,4,400,4,400,4,400,4,400,7,1,400,0,400,319,0,400,0,400,0,400,0,400,0,0,400,2,400,319,0,400,0,400,0,400,0,400,0,0,400,11,400,319,4,400,4,400,6,400,4,400,0,0,400,30,400,400,0,400,0,400,0,400,0,400,5,5,400,23,400,319,0,400,0,400,0,400,0,400,0,0,400,9,400,319,6,400,2,400,3,400,6,400,0,0,400,43,400,0,0,400,0,0,400,1,1,320,43,10,44,37,43,400,3,3,3,0,3,0,0,0,0,400,41,400,0,0,400,3,3,400,4,3,324,42,13,52,29,40,400,3,3,3,0,3,0,0,0,0,400,79,400,17,3,400,0,0,400,0,0,325,60,34,53,33,60,400,23,23,23,0,23,4,0,4,0,400,44,400,2,1,400,5,5,400,0,0,400,46,34,43,16,41,400,8,8,8,0,7,4,0,4,0,400,1,400,114,400,32,32,400,10,8,400,15,12,400,47,44,50,7,50,400,62,56,115,0,36,4,3,4,1,400,9,400,0,0,400,0,0,400,11,7,400,0,0,0,0,0,319,91,6,10,0,8,0,0,5,5,400,52,400,0,0,400,11,11,400,15,14,385,34,3,33,32,32,400,38,35,37,1,37,16,16,16,15,400,69,394,7,7,395,5,4,400,0,0,400,111,72,76,4,71,400,3,3,3,0,3,0,0,0,0,400,75,400,2,2,400,1,0,400,0,0,400,74,68,68,10,73,400,0,0,0,0,0,0,0,0,0,400,4,400,0,0,400,0,0,400,0,0,400,4,4,4,0,4,319,81,0,0,0,0,0,0,0,0,94,5,5,94,2,2,96,11,11,400,0,65,1,4,400,0,20,2,4,398,0,74,327,54,13,237,252,44,31,31,245,0,0,326,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,34,22,22,34,34,0,18,8,0,0,30,34,34,34,9,34,8,34,6,34,9,34,2,3,34,21,34,34,8,34,6,34,8,34,8,34,0,0,34,26,34,31,12,30,8,34,6,34,9,34,0,0,34,16,34,31,9,34,8,34,6,34,9,34,0,0,34,0,34,17,34,31,9,34,8,34,6,34,8,34,0,0,34,1,34,30,0,34,0,34,0,34,0,34,0,0,34,11,34,30,0,34,0,34,0,34,0,34,0,0,34,6,34,30,4,34,4,34,6,34,4,34,0,0,34,15,34,34,4,34,4,34,4,34,4,34,0,0,34,14,34,31,5,34,4,34,4,34,4,34,0,0,34,4,34,30,3,34,1,34,2,34,3,34,0,0,34,2,34,0,0,34,0,0,34,0,0,30,2,1,2,1,2,34,0,0,0,0,0,0,0,0,0,34,1,34,0,0,34,0,0,34,1,0,30,1,0,3,2,1,34,0,0,0,0,0,0,0,0,0,34,2,34,0,0,34,0,0,34,0,0,30,3,1,2,2,3,34,1,1,1,0,1,0,0,0,0,34,1,34,0,0,34,0,0,34,0,0,34,1,1,0,0,1,34,1,1,1,0,1,0,0,0,0,34,0,34,3,34,0,0,34,0,0,34,0,0,34,2,2,2,0,2,34,2,1,6,0,2,0,0,0,0,34,0,34,0,0,34,0,0,34,0,0,34,0,0,0,0,0,30,4,0,0,0,0,0,0,0,0,34,3,34,0,0,34,0,0,34,1,1,33,3,0,3,3,3,34,2,2,1,0,1,0,0,0,0,34,5,33,0,0,33,0,0,34,0,0,34,5,5,5,0,5,34,0,0,0,0,0,0,0,0,0,34,6,34,0,0,34,0,0,34,0,0,34,6,6,6,0,6,34,0,0,0,0,0,0,0,0,0,34,0,34,0,0,34,0,0,34,0,0,34,0,0,0,0,0,30,4,0,0,0,0,0,0,0,0,4,0,0,4,0,0,4,0,0,34,0,3,0,0,34,0,1,0,0,31,0,9,22,2,2,18,18,1,1,1,18,1,1,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [4]:
data_df.head(5)

,agreement_id,Item_letter,Item_number,item_type,item,facility,weapon_item_definition,c_weapon_item_definition,subcategory,subcategory_main,summary_category,ban_development,c_ban_development,ban_development_execution_type,ban_development_assistance_grant,c_ban_development_assistance_grant,ban_development_assistance_gain,c_ban_development_assistance_gain,ban_development_permission,c_ban_development_permission,ban_development_execution,c_ban_development_execution,ban_development_party,ban_development_party_specific,c_ban_development_party_specific,ban_testing,c_testing_,ban_testing_execution_type,ban_testing_assistance_grant,c_ban_testing_assistance_grant,ban_testing_assistance_gain,c_ban_tesing_assistance_gain,ban_testing_permission,c_ban_testing_permission,ban_testing_execution,c_ban_testing_execution,ban_testing_party,ban_testing_party_specific,c_ban_testing_party_specific,ban_production,c_ban_production,ban_production_execution_type,ban_production_assistance_grant,c_ban_priduction_assistance_grant,ban_production_assistance_gain,c_ban_production_assistance_gain,ban_production_permission,c_ban_production_permission,ban_production_execution,c_ban_production_execution,ban_production_party,ban_production_party_specific,c_ban_production_party_specific,ban_acquisition,c_ban_acquisition,ban_acquisition_execution_type,ban_acquisition_assistance_grant,c_ban_acquisition_assistance_grant,ban_acquisition_assistance_gain,c_ban_acquisition_assistance_gain,ban_acquisition_permission,c_ban_acquisition_permission,ban_acquisition_execution,c_ban_acquisition_execution,ban_acquisition_party,ban_acquisition_party_specific,c_ban_acquisition_party_specific,ban_possession,c_ban_possession,ban_possession_general,c_ban_possession_general,ban_possession_general_execution_type,ban_possession_general_assistance_grant,c_ban_possession_general_assistance_grant,ban_possession_general_assistance_gain,c_ban_possession_general_assistance_gain,ban_possession_general_permission,c_ban_possession_general_permission,ban_possession_general_execution,c_ban_possession_general_execution,ban_possession_party,ban_possession_party_specific,c_ban_possession_party_specific,ban_possession_non_deployed,c_ban_possession_non_deployed,ban_possession_non_deployed_execution_type,ban_possession_non_deployed_assistance_grant,c_ban_possession_non_deployed_assistance_grant,ban_possession_non_deployed_assistance_gain,c_ban_possession_non_deployed_assistance_gain,ban_possession_non_deployed_permission,c_ban_possession_non_deployed_permission,ban_possession_non_deployed_execution,c_ban_possession_non_deployed_execution,ban_possession_non_deployed_party,ban_possession_non_deployed_party_specific,c_ban_possession_non_deployed_party_specific,ban_possession_deployed,c_ban_possession_deployed,ban_possession_deployed_execution_type,ban_possession_deployed_assistance_grant,c_ban_possession_deployed_assistance_grant,ban_possession_deployed_assistance_gain,c_ban_possession_deployed_assistance_gain,ban_possession_deployed_permission,c_ban_possession_deployed_permission,ban_possession_deployed_execution,c_ban_possession_deployed_execution,ban_possession_deployed_party,ban_possession_deployed_party_specific,c_ban_possession_deployed_party_specific,ban_station,c_ban_station,ban_station_execution_type,ban_station_assistance_grant,c_ban_station_assistance_grant,ban_station_assistance_gain,c_ban_station_assistance_gain,ban_station_permission,c_ban_station_permission,ban_station_execution,c_ban_station_execution,ban_station_party,ban_station_party_specific,c_ban_station_party_specific,ban_transfer,c_ban_transfer,ban_transfer_execution_type,ban_transfer_assistance_grant,c_ban_transfer_assistance_grant,ban_transfer_assistance_gain,c_ban_transfer_assistance_gain,ban_transfer_permission,c_ban_transfer_permission,ban_transfer_execution,c_ban_transfer_execution,ban_transfer_party,ban_transfer_party_specific,c_ban_transfer_party_specific,ban_use,c_ban_use,ban_use_execution_type,ban_use_assistance_grant,c_ban_use_assistance_grant,ban_use_assistance_gain,c_ban_use_assistance_gain,ban_use_permission,c_ban_use_permission,ban_use_execution,c_ban_use_execution,ban_use_party,ban_use_party_specific,c_ban_use_party_specific,ban_disposal,c_ban_disposal,ban_disposal_interaction_type,ban_disposal_assistance_grant,c_ban_disposal_assistance_grant,ban_disposal_assistance_gain,c_ban_disposal_assistance_gain,ban_disposal_permission,c_ban_disposal_permission,ban_disposal_execution,c_ban_disposal_execution,ban_disposal_party,ban_disposal_party_specific,c_ban_disposal_party_specific,restriction_development,c_restriction_development,restriction_development_party,restriction_development_party_specific,c_restriction_development_party_specific,restriction_development_location,restriction_development_location_specific,c_restriction_development_location_specific,restriction_development_facility,restriction_development_facility_specific,c_restriction_development_facility_specific,restriction_development_quality,restriction_development_quality_practice,restriction_development_quality_practice_specified,restriction_development_quality_capability,restriction_development_quality_capability_specific,c_restriction_development_quality_specific,restriction_development_quantity,restriction_development_quantity_specific,c_restriction_development_quantity_specific,restriction_development_quantity_type,restriction_development_quantity_type_other,c_restriction_development_quantity_type,restriction_development_item_counting,c_restriction_development_item_counting,restriction_development_item_counting_point,c_restriction_development_item_counting_point,testing_restriction,c_testing_restriction,restriction_testing_party,restriction_testing_party_specific,c_restriction_testing_party_specific,restriction_testing_location,restriction_testing_location_specific,c_restriction_testing_location_specific,restriction_testing_facility,restriction_testing_facility_specific,c_restriction_testing_facility_specific,restriction_testing_quality,restriction_testing_quality_practice,restriction_testing_quality_practice_specified,restriction_testing_quality_capability,restriction_testing_quality_capability_specific,c_restriction_testing_quality_specific,restriction_testing_quantity,restriction_testing_quantity_specific,c_restriction_testing_quantity_specific,restriction_testing_quantity_type,restriction_testing_quantity_type_other,c_restriction_testing_quantity_type,restriction_testing_item_counting,c_restriction_testing_item_counting,restriction_testing_item_counting_point,c_restriction_testing_item_counting_point,restriction_production,c_restriction_production,restriction_production_party,restriction_production_party_specific,c_restriction_production_party_specific,restriction_production_location,restriction_production_location_specific,c_restriction_production_location_specific,restriction_production_facility,restriction_production_facility_specific,c_restriction_production_facility_specific,restriction_production_quality,restriction_production_quality_practice,restriction_production_quality_practice_specified,restriction_production_quality_capability,restriction_production_quality_capability_specific,c_restriction_production_quality_specific,restriction_production_quantity,restriction_production_quantity_specific,c_restriction_production_quantity_specific,restriction_production_quantity_type,restriction_production_quantity_type_other,c_restriction_production_quantity_type,restriction_production_item_counting,c_restriction_production_item_counting,restriction_production_item_counting_point,c_restriction_production_item_counting_point,restriction_acquisition,c_restriction_acquisition,restriction_acquisition_party,restriction_acquisition_party_specific,c_restriction_acquisition_party_specific,restriction_acquisition_location,restriction_acquisition_location_specific,c_restriction_acquisition_location_specific,restriction_acquisition_facility,restriction_acquisition_facility_specific,c_restriction_acquisition_facility_specific,restriction_acquisition_quality,restriction_acquisition_quality_practice,restriction_acquisition_quality_practice_specified,restriction_acquisition_quality_capability,restriction_acquisition_quality_capability_specific,c_restriction_acquisition_quality_specific,restriction_acquisition_quantity,restriction_acquisition_quantity_specific,c_restriction_acquisition_quantity_specific,restriction_acquisition_quantity_type,restriction_acquisition_quantity_type_other,c_restriction_acquisition_quantity_type,restriction_acquisition_item_counting,c_restriction_acquisition_item_counting,restriction_acquisition_item_counting_point,c_restriction_acquisition_item_counting_point,restriction_possession,c_restriction_possession,restriction_possession_general,c_restriction_possession_general,restriction_possession_general_party,restriction_possession_general_party_specific,c_restriction_possession_general_party_specific,restriction_possession_general_location,restriction_possession_general_location_specific,c_restriction_possession_general_location_specific,restriction_possession_general_facility,restriction_possession_general_facility_specific,c_restriction_possession_general_facility_specific,restriction_possession_general_quality,restriction_possession_general_quality_practice,restriction_possession_general_quality_practice_specified,restriction_possession_general_quality_capability,restriction_possession_general_quality_capability_specific,c_restriction_possession_general_quality_specific,restriction_possession_general_quantity,restriction_possession_general_quantity_specific,c_restriction_possession_general_quantity_specific,restriction_possession_general_quantity_type,restriction_possession_general_quantity_type_other,c_restriction_possession_general_quantity_type,restriction_possession_general_item_counting,c_restriction_possession_general_item_counting,restriction_possession_general_item_counting_point,c_restriction_possession_general_item_counting_point,restriction_possession_non_deployed,c_restriction_possession_non_deployed,restriction_possession_non_deployed_party,restriction_possession_non_deployed_party_specific,c_restriction_possession_non_deployed_party_specific,restriction_possession_non_deployed_location,restriction_possession_non_deployed_location_specific,c_restriction_possession_non_deployed_location_specific,restriction_possession_non_deployed_facility,restriction_possession_non_deployed_facility_specific,c_restriction_possession_non_deployed_facility_specific,restriction_possession_non_deployed_quality,restriction_possession_non_deployed_quality_practice,restriction_possession_non_deployed_quality_practice_specified,restriction_possession_non_deployed_quality_capability,restriction_possession_non_deployed_quality_capability_specific,c_restriction_possession_non_deployed_quality_specific,restriction_possession_non_deployed_quantity,restriction_possession_non_deployed_quantity_specific,c_restriction_possession_non_deployed_quantity_specific,restriction_possession_non_deployed_quantity_type,restriction_possession_non_deployed_quantity_type_other,c_restriction_possession_non_deployed_quantity_type,restriction_possession_non_deployed_item_counting,c_restriction_possession_non_deployed_item_counting,restriction_possession_non_deployed_item_counting_point,c_restriction_possession_non_deployed_item_counting_point,restriction_possession_deployed,c_restriction_possession_deployed,restriction_possession_deployed_party,restriction_possession_deployed_party_specific,c_restriction_possession_deployed_party_specific,restriction_possession_deployed_location,restriction_possession_deployed_location_specific,c_restriction_possession_deployed_location_specific,restriction_possession_deployed_facility,restriction_possession_deployed_facility_specific,c_restriction_possession_deployed_facility_specific,restriction_possession_deployed_quality,restriction_possession_deployed_quality_practice,restriction_possession_deployed_quality_practice_specified,restriction_possession_deployed_quality_capability,restriction_possession_deployed_quality_capability_specific,c_restriction_possession_deployed_quality_specific,restriction_possession_deployed_quantity,restriction_possession_deployed_quantity_specific,c_restriction_possession_deployed_quantity_specific,restriction_possession_deployed_quantity_type,restriction_possession_deployed_quantity_type_other,c_restriction_possession_deployed_quantity_type,restriction_possession_deployed_item_counting,c_restriction_possession_deployed_item_counting,restriction_possession_deployed_item_counting_point,c_restriction_possession_deployed_item_counting_point,restriction_transfer,c_restriction_transfer,restriction_transfer_party,restriction_transfer_party_specific,c_restriction_transfer_party_specific,restriction_transfer_location,restriction_transfer_location_specific,c_restriction_transfer_location_specific,restriction_transfer_facility,restriction_transfer_facility_specific,c_restriction_transfer_facility_specific,restriction_transfer_quality,restriction_transfer_quality_practice,restriction_transfer_quality_practice_specified,restriction_transfer_quality_capability,restriction_transfer_quality_capability_specific,c_restriction_transfer_quality_specific,restriction_transfer_quantity,restriction_transfer_quantity_specific,c_restriction_transfer_quantity_specific,restriction_transfer_quantity_type,restriction_transfer_quantity_type_other,c_restriction_transfer_quantity_type,restriction_transfer_item_counting,c_restriction_transfer_item_counting,restriction_transfer_item_counting_point,c_restriction_transfer_item_counting_point,restriction_use,c_restriction_use,restriction_use_party,restriction_use_party_specific,c_restriction_use_party_specific,restriction_use_location,restriction_use_location_specific,c_restriction_use_location_specific,restriction_use_facility,restriction_use_facility_specific,c_restriction_use_facility_specific,restriction_use_quality,restriction_use_quality_practice,restriction_use_quality_practice_specified,restriction_use_quality_capability,restriction_use_quality_capability_specific,c_restriction_use_quality_specific,restriction_use_quantity,restriction_use_quantity_specific,c_restriction_use_quanity_specific,restriction_use_quantity_type,restriction_use_quantity_type_other,c_restriction_use_quantity_type,restriction_use_item_counting,c_restriction_use_item_counting,restriction_use_item_counting_point,c_restriction_use_item_counting_point,restriction_disposal,c_restriction_disposal,restriction_disposal_party,restriction_disposal_party_specific,c_restriction_disposal_party_specific,restriction_disposal_location,restriction_disposal_location_specific,c_restriction_disposal_location_specific,restriction_disposal_facility,restriction_disposal_facility_specific,c_restriction_disposal_facility_specific,restriction_disposal_quality,restriction_disposal_quality_practice,restriction_disposal_quality_practice_specified,restriction_disposal_quality_capability,restriction_disposal_quality_capability_specific,c_restriction_disposal_quality_specific,restriction_disposal_quantity,restriction_disposal_quantity_specific,c_restriction_disposal_quanity_specific,restriction_disposal_quantity_type,restriction_disaposal_quantity_type_other,c_restriction_disposal_quantity_type,restriction_disaposal_item_counting_point,c_restriction_disaposal_item_counting_point,restriction_disposal_item_counting_point,c_restriction_disposal_item_counting_point,facility_destruction,facility_destruction_specified,c_facility_destriction,facility_conversion,facility_conversion_specified,c_facility_conversion,facility_use,facility_use_specified,c_facility_use,eliminitation,elimination_procedure,c_elimination,point_of_elimination,c_point_of_elimination,conversion,conversion_procedure,c_conversion_procedure,point_of_conversion,c_point_of_conversion,modernization,modernization_other,c_modernization,obligations_timeframe_type,timeframe_set_time,timeframe_other,c_obligations_timeframe,timeframe_phases,c_timeframe_phases,phases_number,c_phases,timeframe_obligations_extention,timeframe_obligations_extention_specified,c_timeframe_obligations_extention_specified,excepetions,excepetions_specified,c_excpetions,Unnamed: 475,Unnamed: 476,Unnamed: 477,Unnamed: 478,Unnamed: 479,Unnamed: 480,Unnamed: 481,Unnamed: 482,Unnamed: 483,Unnamed: 484,Unnamed: 485,Unnamed: 486,Unnamed: 487,Unnamed: 488,Unnamed: 489,Unnamed: 490,Unnamed: 491,Unnamed: 492,Unnamed: 493,Unnamed: 494,Unnamed: 495,Unnamed: 496,Unnamed: 497,Unnamed: 498,Unnamed: 499,Unnamed: 500,Unnamed: 501
0,40,A,1.0,1.0,Weapons General,NaN,99,NaN,NaN,NaN,0.0,0,NaN,0,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,0.0,NaN,0.0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,0.0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,NaN,0,0.0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,0.0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,0.0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,0.0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,0.0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,0.0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0.0,NaN,NaN,0.0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Iid. Article I: The Contracting Parties confir...,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,1,1.0,Quality-specific Use-restriction: restricting ...,0.0,NaN,Ibid. Article I: The Contracting Parties confi...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,0.0,NaN,NaN,Assumed directly upon force given no explicit ...,0.0,NaN,NaN,NaN,2.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN